### ISSUE TITLE
VideoPlayerRenderer on Android not being called

### ISSUE THREAD

**Issue by teracat** [adamfisher/Xamarin.Forms.VideoPlayer#1]
Hello,

First things first: thank you for this great component.

I'm trying to set the Source from an Expansion File in Android. Because of I can't get it working using the VideoSource, I tried to use a custom VideoPlayerRenderer which is not called.

I declare the ExportRenderer as follows:

`[assembly: ExportRenderer(typeof(VideoPlayer), typeof(CustomVideoPlayerRenderer))]`

And implement the class:

```
public class CustomVideoPlayerRenderer : VideoPlayerRenderer
    {
        protected override void OnElementPropertyChanged(object sender, PropertyChangedEventArgs e)
        {
            if (e.PropertyName == VideoPlayer.SourceProperty.PropertyName)
            {
...
```

The OnElementPropertyChanged method is never called.

I create the VideoPlayer as follows:

```
xVideoPlayer = new VideoPlayer();
xVideoPlayer.AutoPlay = false;
xVideoPlayer.DisplayControls = false;
xVideoPlayer.FillMode = Octane.Xam.VideoPlayer.Constants.FillMode.Resize;
```

And adds it to a RelativeLayout.

I'm using Xamarin Forms 2.3.3.180 (I have checked and it's the same version for the Android and PCL projects).

I have another Custom Renderer (for Button) and it gets called right.

**Comment by teracat** [comment]
I attach a sample project to reproduce the problem:

[AndroidVideoPlayerRenderer.zip](https://github.com/adamfisher/Xamarin.Forms.VideoPlayer/files/764015/AndroidVideoPlayerRenderer.zip)

I'm using VideoPlayer v1.2.1 and testing it on a Tablet with Android 4.4.2

**Comment by adamfisher** [comment]
In order for Xamarin Forms to pick up a custom renderer, you need to create a new class type in the portable class library as well and have it extend `VideoPlayer` and lets assume you call it `MyVideoPlayer` then your custom renderer declaration becomes:

```
[assembly: ExportRenderer(typeof(MyVideoPlayer), typeof(CustomVideoPlayerRenderer))]
```

The class can be empty but it must exist so Xamarin Forms can map it to your custom control.

**Comment by teracat** [comment]
Now the custom renderer is being called when using my own class extending VideoPlayer, thank you! But I can't make it work with the Expansion File.

By now, I don't use a custom renderer to load a video from an Expansion File. This is what I do:

```
var files = ApkExpansionSupport.GetApkExpansionZipFile(Xamarin.Forms.Forms.Context, 3, 0);
var entry = files.GetEntry(video);
VideoZipFile = new ZipFile(entry.ZipFileName);
VideoStream = VideoZipFile.ReadFile(entry);                    

return VideoSource.FromStream(() => VideoStream, "mp4");
```

More about this on this page: https://dotnetdevaddict.co.za/2014/12/21/downloading-expansion-files-in-xamarin-android/

VideoZipFile & VideoStream are static variables and they are disposed before accessing a new video or when the app is closed (or when no video is being watched).

But after some tests, it takes too much time to load the video and the app freezes while it's being loaded (when Source is assigned), so: @adamfisher is there a better way to load a video from a obb file (zip with no compression) to be used with the VideoPlayer?

**Comment by teracat** [comment]
Finally, I got it working with the content provider and the video is loaded much faster. This is my custom renderer:

```
public class CustomVideoPlayerRenderer : VideoPlayerRenderer
{
    protected override void OnElementChanged(ElementChangedEventArgs<VideoPlayer> e)
    {
        base.OnElementChanged(e);
        UpdateVideoSource();
    }

    protected override void OnElementPropertyChanged(object sender, PropertyChangedEventArgs e)
    {
        base.OnElementPropertyChanged(sender, e);
        if (e.PropertyName == VideoPlayer.SourceProperty.PropertyName)
            UpdateVideoSource();
    }

    private void UpdateVideoSource()
    {
        var element = Element as VideoPlayer;
        if (element == null || Control == null || element.Source == null)
            return;

        var fileSource = element.Source as FileVideoSource;
        var uri = Uri.Parse("content://" + ZipFileContentProvider.ContentProviderAuthority + "/" + fileSource.File);
        Control.SetVideoURI(uri);
    }
}
```

The Source of the VideoPlayer is set using VideoSource.FromFile("video_name.mp4")
