### ISSUE TITLE
Android (FillMode) Video Resolution Appears Stretched

### ISSUE THREAD

**Issue by shayo** [adamfisher/Xamarin.Forms.VideoPlayer#10]
When I turn my Android device to landscape and then back to portrait while a movie is playing it screws up the video aspect ratio (becomes stretched).
Solution?

**Comment by adamfisher** [comment]
Unfortunately Android was not very easy for aspect ratio. This issue was originally documented in the old issue tracker with a potential workaround:

https://bitbucket.org/OctaneSoftware/octane.xam.videoplayer/issues/2/android-fillmode-video-resolution-appears
