### ISSUE TITLE
TimeElapsed Event Fires Immediately on IOS even when Interval is 30; Never on Android

### ISSUE THREAD

**Issue by eopeter** [adamfisher/Xamarin.Forms.VideoPlayer#100]
I have set the TimeElapsedInterval value to 30 but on iOS it fires the TimeElapsed event immediately and multiple times after. On Android, it never fires. Want I would like is to hide some controls after 30 seconds of play time. 

Any help is appreciated.

Thanks
Emmanuel

**Comment by adamfisher** [comment]
Are you saying you wish to hide the controls indefinitely after 30 seconds? If so, `DisplayControls="False"` will help. It is only for when you want to complete enable or disable the controls. 

But if you are just simply wanting to trigger the controls to disappear but still re-appear once the user interacts with the player again, you would want to use a Xamarin Forms custom renderer to get at the native media controller on Android to trigger it to "hide". You can take a look at extending `VideoPlayerRenderer` in your Android project to accomplish it.

**Comment by adamfisher** [comment]
As for the timing issue, are you setting the time interval before play is pressed or the stream is loaded? Or do you set it in XAML along with everything else on the player? If you can share your snippet that would help. I think that might work for now to specify the time interval before the video is loaded. I do see a potential issue.

**Comment by eopeter** [comment]
I set the TimeElapsedInterval in XAML just like the Sample code in the Getting Started section of the ReadMe. What I expect is for the timer to fire after the TimeElapsedInterval but fired right away in iOS after the source is set. It never fires on Android after 30 seconds. 

`
<Octane:VideoPlayer
	AutoPlay="False"
	DisplayControls="True|False"
	FillMode="ResizeAspectFill"
	TimeElapsedInterval="30" TimeElapsed="VideoPlayer_OnTimeElapsed"
	Repeat="False" />
`

**Comment by eopeter** [comment]
Any update on this? Thanks

**Comment by adamfisher** [comment]
I setup the following example in the Chill Player example app as below and it was successfully invoking the event method every 5 seconds.

**FullScreenVideoPlayerPage.xaml:**
```csharp
<o:VideoPlayer x:Name="videoPlayer" Source="{me:VideoResource video.mp4}" 
AutoPlay="True" TimeElapsedInterval="5" TimeElapsed="VideoPlayer_OnTimeElapsed" />
```
**FullScreenVideoPlayerPage.xaml.cs:**
```csharp
private void VideoPlayer_OnTimeElapsed(object sender, VideoPlayerEventArgs e)
{
   DisplayAlert("Hello!", "It has been a 5 second period!", "OK Cool").Start();
}
```

**Comment by eopeter** [comment]
Ok, I'll try again

**Comment by adamfisher** [comment]
As for iOS doing an initial firing when playback starts, this functionality is integrated directly into Apple's `AVPlayer` as opposed to Android which implements a separate timer to achieve interval firings. Either adjusting Android to do an extra firing at the beginning or tweaking iOS to throw away its initial firing would be a breaking change to the behavior users expect today so I am reluctant to change it at this point. I do agree with you it seems iOS should throw away that initial firing.

According to iOS documentation, the `PeriodicTimeObserver` (which powers the timed interval firings on iOS) behaves like this:

> Invoked periodically at the interval specified, interpreted according to the timeline of the current item. The block is also invoked whenever time jumps and whenever playback starts or stops. If the interval corresponds to a very short interval in real time, the player may invoke the block less frequently than requested. Even so, the player will invoke the block sufficiently often for the client to update indications of the current time appropriately in its end-user interface.

One possibility might be to look at the current time to ensure it is 30 seconds or later to ensure you do nothing on the initial firing.

```csharp
private void VideoPlayer_OnTimeElapsed(object sender, VideoPlayerEventArgs e)
{
   var tolerance = 2;
   if (Math.Abs(e.CurrentTime.TotalSeconds - 30) < tolerance)
   {
      // do something 30 seconds or into the video
   }
}
```
