### ISSUE TITLE
Binding youtube video with the MakupExtention

### ISSUE THREAD

**Issue by Mythxir** [adamfisher/Xamarin.Forms.VideoPlayer#101]
Im trying to bind a youtube video to one of my vieuws but it cant seem to find the right syntax to bind the value into the MarkupExtention could you help me with this ?
`<o:VideoPlayer Source="e:YouTubeVideoId {Binding url}" />
<o:VideoPlayer Source="{e:YouTubeVideoId {Binding url}}" />
<o:VideoPlayer Source="{Binding e:YouTubeVideoId  url}" />`

**Comment by Mythxir** [comment]
Seems we were able to fix it using a custom binding
`<local:YoutubeVideo VideoID="{Binding url}"/>`

**Comment by raf66** [comment]
Hello Mythxir,
Any change you can share your solution?
