### ISSUE TITLE
Why buy ?

### ISSUE THREAD

**Issue by ghost** [adamfisher/Xamarin.Forms.VideoPlayer#103]
Hi,

I search for a repliable video player for XF. I found that https://github.com/martijn00/XamarinMediaManager

and yours.

What makes yours so outstanding to invest 65 bucks in comparison to the open source one?

Thanks in advance for your reply.
Best
Eric

**Comment by adamfisher** [comment]
You might take a look at the [Getting Started Guide](https://github.com/adamfisher/Xamarin.Forms.VideoPlayer/blob/master/GettingStarted.md). This player supports many properties and events other players do not expose. It also has support for WIndows platforms if that is important to you.

Ultimately it comes down to choosing the library that best fits your needs and budget.
