### ISSUE TITLE
Build error

### ISSUE THREAD

**Issue by scastria** [adamfisher/Xamarin.Forms.VideoPlayer#105]
I am confused by the error below from VS 2017 enterprise on Windows 10.  I am not building for AMD64, but for x64.  And even if I was building for AMD64, why is x86 version of Octane being used?  Does Octane not include support for AMD platform?  I am not an experience VS user on Windows so any suggestions would help.

Error		There was a mismatch between the processor architecture of the project being built "AMD64" and the processor architecture of the reference "C:\Users\suq41198\.nuget\packages\octane.xam.videoplayer\2.1.0\lib\UAP10\Octane.Xamarin.Forms.VideoPlayer.UWP.dll", "x86". This mismatch may cause runtime failures. Please consider changing the targeted processor architecture of your project through the Configuration Manager so as to align the processor architectures between your project and references, or take a dependency on references with a processor architecture that matches the targeted processor architecture of your project.	FDCapture.UWP

**Comment by scastria** [comment]
I think I confused AMD with ARM.  I guess AMD64 and x64 are compatible.  So maybe the real question is does octane support 64bit platforms?

**Comment by scastria** [comment]
This is not a free component.  I would have hoped for some response on this bug after 22 days.

**Comment by adamfisher** [comment]
Consolidating this to #113 for tracking.

I believe setting your target platform to AnyCPU may help. The release of the fall creator's update seemed to have affected things.
