### ISSUE TITLE
ChillPlayer sample doesn't compile on iOS

### ISSUE THREAD

**Issue by scastria** [adamfisher/Xamarin.Forms.VideoPlayer#107]
/Library/Frameworks/Mono.framework/External/xbuild/Xamarin/iOS/Xamarin.iOS.Common.targets(3,3): Error:   Bundle Resource 'Icon-60@3x.png' not found on disk (should be at '/GIT/Xamarin.Forms.VideoPlayer/ChillPlayer/ChillPlayer.iOS/Resources/Icon-60@3x.png') (ChillPlayer.iOS)
/Library/Frameworks/Mono.framework/External/xbuild/Xamarin/iOS/Xamarin.iOS.Common.targets(3,3): Error:   Bundle Resource 'Icon-Small-40@3x.png' not found on disk (should be at '/GIT/Xamarin.Forms.VideoPlayer/ChillPlayer/ChillPlayer.iOS/Resources/Icon-Small-40@3x.png') (ChillPlayer.iOS)
/Library/Frameworks/Mono.framework/External/xbuild/Xamarin/iOS/Xamarin.iOS.Common.targets(3,3): Error:   Bundle Resource 'Icon-Small@3x.png' not found on disk (should be at '/GIT/Xamarin.Forms.VideoPlayer/ChillPlayer/ChillPlayer.iOS/Resources/Icon-Small@3x.png') (ChillPlayer.iOS)

**Comment by adamfisher** [comment]
Duplicate of #109 and will be tracked there.

**Comment by adamfisher** [comment]
This issue should be resolved now with the latest commit.
