### ISSUE TITLE
ChillPlayer sample doesn't compile on Android

### ISSUE THREAD

**Issue by scastria** [adamfisher/Xamarin.Forms.VideoPlayer#108]
/GIT/Xamarin.Forms.VideoPlayer/ChillPlayer/ChillPlayer.Android/obj/Debug/android/manifest/AndroidManifest.xml(0,0): Error APT0000: No resource found that matches the given name (at 'theme' with value '@style/MainTheme'). (APT0000) (ChillPlayer.Android)

**Comment by adamfisher** [comment]
Duplicate of #109 and will be tracked there.

**Comment by adamfisher** [comment]
This issue should be resolved now with the latest commit.
