### ISSUE TITLE
Question: Is there a way to get the resolution of the underlying video stream?

### ISSUE THREAD

**Issue by OhzeeCreative** [adamfisher/Xamarin.Forms.VideoPlayer#11]

**Comment by adamfisher** [comment]
There is no cross-platform way to get the resolution currently. You could create a custom renderer to expose it. Under the hood, Android uses `VideoView`, iOS uses `AVPlayer`, and Windows Phone uses `MediaElement` so depending on which platforms you are targeting, you would just need to see which methods return the resolution on this objects.

```csharp
public class MyVideoPlayerRenderer : VideoPlayerRenderer 
{
    // Add method to access something like: Control.NativeMethodToGetResolution()
}
```
