### ISSUE TITLE
Tried to purchase the video player

### ISSUE THREAD

**Issue by jeffgrau** [adamfisher/Xamarin.Forms.VideoPlayer#115]
What kind of nonsense are the license requirements. I will be in development for the next 6 months and have no idea of the identification required for release to the app stores. 15 seconds of video during development is very unacceptable. I spent 2 days evaluating your product and designed iOS and UWP renderers to meet my needs. Now I am told I need to live with 15 seconds until release. What about alpha testing, or initial release to a single platform. What about the UWP app which will be spawned from a WinForms Application. I saw only WindowsPhone as an option. The UWP app will not even be distributed through an App store, but part of a general software release.  I assume you will refund my purchase or contact me to make acceptable arrangements.

**Comment by adamfisher** [comment]
Hello Jeff - Linking the license key to the bundle identifier is the only way that has been identified so far to ensure the player is only ever used with a single mobile application since the app stores require those to be unique per app.

I suppose for the future we could also consider changing the 15 second limit to accommodate a total duration of some amount of time such as one week before causing an `InvalidLicenseException`.

I can certainly refund the license if the player does not fit your requirements. I have sent you an email with details.

**Comment by jeffgrau** [comment]
Hi Adam,
   I found a hack around your 15 second limit (it does cause a blip at the 15 second point, so it is no good for production). With the hack, I can use the control for development and once I am ready to go into production, I will have the information needed to fill out the forms. So assuming that there is a way I can use it in the UWP version which will not be released in an app store and assuming my purchase will still be good in 6 months, there is no reason to refund the money. If there is no way to handle UWP licensing, perhaps we can come to a private agreement for slightly more money. You also have my word that the Octane Player will only be used in a single application called NowSeeHere. Your video player is quite good and the only acceptable candidate. Once NowSeeHere goes into production I will have no problem paying you additional funds, and if my dreams come true, paying a significant annual support fee.
Jeff
P.S. For your future info, here is the hack in the renderer (Don’t worry, I won’t tell anybody).

protected override void OnElementPropertyChanged(object sender, PropertyChangedEventArgs e)
       {
           // HAck to get around 15 seconds. Remove when license purhased
           if (e.PropertyName == "CurrentTime")
           {
               VideoPlayer v = (VideoPlayer)sender;
               if (_playerView.Position.TotalSeconds > 14 && _playerView.Position.TotalSeconds < 15.02)
               {
                   _playerView.Position = TimeSpan.FromSeconds(15.01);
                   return;
               }
           }
           base.OnElementPropertyChanged(sender, e);
           if (e.PropertyName == "CurrentTime")
           {
               if (_playerView.NaturalDuration.TimeSpan.TotalSeconds < 0) return;
               OctaneVideoPlayerView fullElement = (OctaneVideoPlayerView)Element;
               fullElement.ViewModel.Duration = _playerView.NaturalDuration.TimeSpan.TotalSeconds;
               fullElement.ViewModel.CurrentPosition = _playerView.Position.TotalSeconds ;
           }
       }
