### ISSUE TITLE
Can't install anymore

### ISSUE THREAD

**Issue by mwallon** [adamfisher/Xamarin.Forms.VideoPlayer#116]
After using this for a while without problems I suddenly get this error when I try to istall or update, can someone help me?
/magnus

"Could not install package 'Octane.Xam.VideoPlayer 2.1.0'. You are trying to install this package into a project that targets '.NETPortable,Version=v4.5,Profile=Profile111', but the package does not contain any assembly references or content files that are compatible with that framework. For more information, contact the package author."

**Comment by adamfisher** [comment]
Duplicate of #91
