### ISSUE TITLE
New logo for Xamarin.Forms.VideoPlayer

### ISSUE THREAD

**Issue by reallinfo** [adamfisher/Xamarin.Forms.VideoPlayer#117]
Hello, I designed a logo for your app. If you like it, i will send you a pr. If there is another logo idea, please tell me. 

![xvideplayer](https://user-images.githubusercontent.com/36298335/39724445-82cdc048-5251-11e8-8d4b-947b9c5b0914.jpg)

**Comment by adamfisher** [comment]
Thank you for your consideration. Those are some pretty cool designs! I'm not currently looking to re-brand but will certainly keep these in mind for the future and let you know 👍
