### ISSUE TITLE
Any plans to support ExoPlayer?

### ISSUE THREAD

**Issue by adrianknight89** [adamfisher/Xamarin.Forms.VideoPlayer#119]
@adamfisher Do you have any plans to support ExoPlayer for Android instead of using the stock api? On older SDKs, ExoPlayer works better and should be the default choice in my opinion for XF apps.

**Comment by adamfisher** [comment]
The goal of this component is to offer the stock video player of each platform in the same way that all of the other controls in the Xamarin Forms library expose the default platform UI controls. 

However, if you desire this customization you might check out this binding library that was created for ExoPlayer. You could simply extend `VideoPlayerRenderer` in your Android project and use the ExoPlayer to power your Android videos by building out a [Xamarin Forms Custom Renderer](https://docs.microsoft.com/en-us/xamarin/xamarin-forms/app-fundamentals/custom-renderer/).

https://github.com/martijn00/ExoPlayerXamarin
