### ISSUE TITLE
Cache downloaded videos

### ISSUE THREAD

**Issue by isurukej** [adamfisher/Xamarin.Forms.VideoPlayer#12]
Is there any way to cache downloaded videos data in this library?

**Comment by adamfisher** [comment]
By default the native players begin to load the media stream as soon as it is assigned to the `Source` property. There may be some caching/buffering built-in. If you want to download and cache media for offline use, you would need to do that yourself and then you could open it by calling it with a path:

```csharp
videoPlayer.Source = VideoSource.FromFile("/Path/To/File");
```
Or by passing it a raw stream as a lambda function:
```csharp
videoPlayer.Source = VideoSource.FromStream(s => ....);
```
