### ISSUE TITLE
Subtitles support.

### ISSUE THREAD

**Issue by kikutano** [adamfisher/Xamarin.Forms.VideoPlayer#120]
Hi, 
i want to buy this plugin but i want to know if supports the subtitles. 

Thanks a lot.

**Comment by adamfisher** [comment]
It should be possible but will require creating a Xamarin Forms custom renderer to extend `VideoPlayerRenderer` in your platform specific-project to expose the functionality you desire. Under the hood, this component is just using Android's `MediaPlayer` and iOS's `AVPlayerViewController` which are the stock/default video UI controls of each platform.

**Comment by kikutano** [comment]
Thank you!
