### ISSUE TITLE
NullReferenceException in ChillPlayer.Android, & FileNotFoundException in ChillPlayer.UWP

### ISSUE THREAD

**Issue by gcadmes** [adamfisher/Xamarin.Forms.VideoPlayer#121]
**# ChillPlayer.Android**
<br>
1. Downloaded the latest ChillPlayer code sample on 5/22/2018.<br>
2. Restored Nuget Packages.<br>
3. Compiled Solution - Success<br>
4. Deployed to real device: Google Nexus 7 (Android 6.0 API 23)<br>
5. Received a System.NullReferenceException: inside MainActivity.OnCreate, LoadApplication(new App())<br>
_(All exceptions are on)_<br>
![chillplayer android](https://user-images.githubusercontent.com/7306719/40380970-55c15268-5daf-11e8-8229-b9d30408fbae.png)

<br><br>
**# ChillPlayer.UWP**<br>

1. Same steps 1- 4<br>
2. Received "Could not load file or assembly 'Octane.Xamarin.Forms.VideoPlayer, Version=2.1.0.0, Culture=neutral, PublicKeyToken=null'. The located assembly's manifest definition does not match the assembly reference. (Exception from HRESULT: 0x80131040).<br>
![chillplayer uwp](https://user-images.githubusercontent.com/7306719/40380975-5a99209a-5daf-11e8-81ad-e64f36087e20.png)
<br><br>
**# Environment**<br>
Microsoft Visual Studio Professional 2017 <br>
Version 15.7.1<br>
VisualStudio.15.Release/15.7.1+27703.2000<br>
Microsoft .NET Framework<br>
Version 4.7.03056<br>
<br>
Xamarin   4.10.0.442 (396b18cef)<br>
Visual Studio extension to enable development for Xamarin.iOS and Xamarin.Android.<br>
<br>
Xamarin Designer   4.12.264 (fc37cd02e)<br>
Visual Studio extension to enable Xamarin Designer tools in Visual Studio.<br>
<br>
Xamarin.Android SDK   8.3.0.19 (HEAD/342b2ce96)<br>
Xamarin.Android Reference Assemblies and MSBuild support.<br>
<br>
Xamarin.iOS and Xamarin.Mac SDK   11.10.1.177 (7e782c1)<br>
Xamarin.iOS and Xamarin.Mac Reference Assemblies and MSBuild support.<br>
<br>
**# Comments**<br>
Firstly, thank you for all your time and effort putting together a cross-platform Video Player.
If I may be brutally honest here...<br>
While It appears you're off to a great start, to monetize a custom control before it's ready for prime time diminishes your revenue opportunities, not just the VideoPlayer, but potentially others controls you might try and monetize in the future.<br><br>
 
That being said, (IMO) a Sample XF app that showcases a custom control should be able to run on all supported platforms with ease. Of course there will be XF compatibility issues, however, there definitely should not be any Unhandled Exceptions that cause the app to crash or not run.<br>
<br>
At any rate, just my $0.02<br>
Keep up the great work! Looking forward to a stable release.<br>

**Comment by adamfisher** [comment]
I tested the Chill Player example application on a real device as well with a fresh checkout from GitHub and it is working for me. Can you provide the full stack trace?

The UWP issue appears to be the same as #121 so you will want to track that there.

**Comment by JRGit4UE** [comment]
**Same error** with fresh clone at `LoadApplication(new App())` 
(Object reference not set to an instance of an object)

on my **Android 8.0** (Huawei Y6 Prime ) 
Microsoft Visual Studio Professional 2017  Version **15.9.5**
VisualStudio.15.Release/15.9.5+28307.280
Microsoft .NET Framework Version 4.7.03056

Mono Debugging for Visual Studio   4.13.12-pre (9bc9548)

Xamarin   **4.12.3.78** (d15-9@a9bbf702f)
Xamarin Designer   4.16.13 (45a16efd4)
Xamarin Templates   1.1.128 (6f5ebb2)
Xamarin.Android SDK   **9.1.5.0** (HEAD/4b951a3e7)

Platform independent video seems to be hard..
