### ISSUE TITLE
Video Player iOS stuck at black screen with a play button

### ISSUE THREAD

**Issue by msl2000** [adamfisher/Xamarin.Forms.VideoPlayer#122]
Hello

I am having some issues with the video player in iOS where the a screen with the video player included just shows a black screen with a play button. Pressing the button does nothing and the play button just sits there with the black background doing nothing.

Android has no issues

Please help.

**Comment by adamfisher** [comment]
Is your URL using HTTP or HTTPS? If HTTP, you will want to make sure you configured app transport security.

https://github.com/adamfisher/Xamarin.Forms.VideoPlayer/blob/master/GettingStarted.md#app-permissions

**Comment by msl2000** [comment]
Spot on. Thanks Adam. Was in fact just an URL issue
