### ISSUE TITLE
Video ID xvideos

### ISSUE THREAD

**Issue by andersonvieiragomeslopes** [adamfisher/Xamarin.Forms.VideoPlayer#124]
I'm trying your plugin, and enjoyed, however, I need to play videos from xvideos.com, the scheme is the same as that of youtube and vimeo, can you help me? And if it works out I want to buy your plugin, can I use it on two different projects as well?

**Comment by adamfisher** [comment]
You might have a look at some other libraries to get an idea of how to get the raw video URL out of the pages so you can pass it into the video player. A quick search on GitHub turned up this PHP snippet that uses regular expressions to extract the video URL from the web page. It is essentially the same thing I did for the YouTube video extension by getting the raw HTML of the page and then parsing it for the URL.

https://github.com/emeidi/extract-youtube-links-and-download/blob/master/youtube-dl/youtube_dl/extractor/xvideos.py

**Comment by adamfisher** [comment]
A single license grants you a set license keys to use for Android, iOS, Windows for a single app idea.
