### ISSUE TITLE
Is posible play mp3 audio files ?

### ISSUE THREAD

**Issue by SantaRita** [adamfisher/Xamarin.Forms.VideoPlayer#125]
Is posible play mp3 audio files ?

**Comment by adamfisher** [comment]
I have heard of some users having success with this. AVPlayer on iOS and MediaPlayer on Android do support audio files out of the box. Obviously some of the features like aspect ratio will not work or be relevant with audio but you can always give the trial from NuGet a go and see if it fits your needs.
