### ISSUE TITLE
Video Plugin Registration

### ISSUE THREAD

**Issue by trebailey3** [adamfisher/Xamarin.Forms.VideoPlayer#126]
Hi Adam,

I need to have my video plug in updated with a new registration.  Video plugin is currently crashing since the license key for the video plugin is for "com.onek.onekapp" and not "app.onek.onekapp". Can you please change the license key on Video plugin to use "app.onek.onekapp"? I purchased the plugin on Feb 24th.

Thanks,
Tony (William) Bailey

**Comment by adamfisher** [comment]
Resolved.
