### ISSUE TITLE
Licence for multiple apps

### ISSUE THREAD

**Issue by matheusmelato** [adamfisher/Xamarin.Forms.VideoPlayer#132]
Hello,

I'm a developer for a company that has multiple apps and we are searching for a player that help us on a few things. After testing your player I saw that a licence can be used by only one app.

Is there an enterprise licence for an unlimited number of apps?

**Comment by adamfisher** [comment]
Each license key is directly validated against the bundle ID inside your app's manifest file. However, some sort of discount pricing may be possible if you are planning to have purchase multiple copies for different apps depending on the volume.
