### ISSUE TITLE
How to support DRM?

### ISSUE THREAD

**Issue by pankaj-nikam** [adamfisher/Xamarin.Forms.VideoPlayer#133]
Hi there,

If we plan to integrate DRM would it require additional things for configuration?

Thanks.
Sincerely Yours,

Pankaj Nikam.

**Comment by adamfisher** [comment]
I'm not familiar with the challenges you may face with this. However the underlying native player is just `AVPlayer` on iOS, `MediaPlayer` on Android, and `MediaElement` on UWP so the documentation for the platforms you plan to target would be relevant. If you do end up needing to customize something with the native player, you can create a Xamarin Forms custom renderer that extends `VideoPlayerRenderer` in your platform-specific project.

A quick search did turn up some resources that might be helpful:

- https://source.android.com/devices/drm
- https://developer.apple.com/streaming/fps

Of course, the easiest thing to do would be to install the nuget package as a trial and see if you are able to play your streams. If there are errors, you should be able to see them in the `Error` property.
