### ISSUE TITLE
activity indicator Android 

### ISSUE THREAD

**Issue by andersonvieiragomeslopes** [adamfisher/Xamarin.Forms.VideoPlayer#134]
How do I put an activity indicator for android in xamarin forms? So the screen does not turn all black while the video does not load.

**Comment by adamfisher** [comment]
You could use the `IsLoading` property as mentioned in the documentation. It should behave similarly to the Xamarin.Forms `Image.IsLoading` property.

https://docs.microsoft.com/en-us/dotnet/api/xamarin.forms.image.isloading?view=xamarin-forms

**Comment by andersonvieiragomeslopes** [comment]
I did it another way, so it does not work on my project, but thanks.
