### ISSUE TITLE
Offline Video (Stored on iOS) Play 

### ISSUE THREAD

**Issue by hjavaher** [adamfisher/Xamarin.Forms.VideoPlayer#136]
Hi,
I was wondering if there is a way to play offline  (stored on the device) videos. I'm setting the "Source" property of the player to the full path of the video:

`file:///var/mobile/Containers/Data/Application/89DE402B-35E8-4E12-AF72-79C4B35046A1/Documents/../Library/test.mov`

but the player shows black and nothing plays. Is this supported? Am I doing something wrong?

Thanks and great job on the plugin!

**Comment by hjavaher** [comment]
I should also mention that I'm doing this on the code behind and not the xaml and the video was just recorded from the camera.

**Comment by adamfisher** [comment]
You can use something like the following to specifically force it to load from a file on the device filesystem:

```csharp
videoPlayer.Source = VideoSource.FromFile("/Path/To/File");
```

**Comment by hjavaher** [comment]
Thank you very much for getting back to me Adam! For those having the same issue, the main problem was the "file://"

Thanks
