### ISSUE TITLE
[Feature] Greyscale

### ISSUE THREAD

**Issue by JMNewsome** [adamfisher/Xamarin.Forms.VideoPlayer#138]
Ability to have a video be displayed as grey-scale, would be highly useful for my project.

**Comment by adamfisher** [comment]
I'm not confident all platforms would support this but you can create a Xamarin Forms custom renderer and extend `VideoPlayerRenderer` if you find this is feasible and expose that functionality in Xamarin Forms.

**Comment by JMNewsome** [comment]
Just trying to support iOS and Android

Can you give me a rough outline on how to do this? I am somewhat lost on how to exactly implement it and access the shader of the video to implement it on
