### ISSUE TITLE
Video player playing issue in one customized device

### ISSUE THREAD

**Issue by SudharsanKrishnamoorthy** [adamfisher/Xamarin.Forms.VideoPlayer#139]
Hi Adam,
We have purchased a license and using this video player.

The video player is working as expected in all device except TC55 device
While playing video in video player we are getting _OnPlayerStateChanged
PlayerState: Initialized
after that eventually getting status of PlayerState: error

Could you please help us to resolve the issue?

Thanks in advance!!!!

**Comment by SudharsanKrishnamoorthy** [comment]
[newTC55DroidInfo.pdf](https://github.com/adamfisher/Xamarin.Forms.VideoPlayer/files/2327441/newTC55DroidInfo.pdf)

Please find the TC55 Device specification document

And also your sample solution is not opening
error like,
There is a missing project subtype.
Subtype: '{A5A43C5B-DE2A-4C0C-9213-0A381AF9435A}' is unsupported by this installation.

C:\Projects\videoplayer\ChillPlayer\ChillPlayer.csproj : error  : The default XML namespace of the project must be the MSBuild XML namespace. If the project is authored in the MSBuild 2003 format, please add xmlns="http://schemas.microsoft.com/developer/msbuild/2003" to the <Project> element. If the project has been authored in the old 1.0 or 1.2 format, please convert it to MSBuild 2003 format.  C:\Projects\videoplayer\ChillPlayer\ChillPlayer.csproj

**Comment by SudharsanKrishnamoorthy** [comment]
How can I get the log for this issue PlayerState: error
The video player is working as expected in all device except TC55 device
Please help us to resolve this issue ASAP

**Comment by dhuynhtek** [comment]
Your device spec:
OS Version: Jelly Bean (4.1.2) 
SDK: 16

I don't know if you changed the Minimim Android version in the Project Properties->Android manifest but from the latest code it targets Android 5.0 Level 21.

**Comment by SudharsanKrishnamoorthy** [comment]
Hi @dhuynhtek,
No, we tried in Android version 4.1.2 and 4.4.4 its working fine in both the version. We are facing issue only on TC55 Device only

**Comment by SudharsanKrishnamoorthy** [comment]
Hi Adam,
Please let me know one more thing, Is this player contains decoders to play or it depends on any hardware or software support from the mobile part?

**Comment by adamfisher** [comment]
The player is using Android's `MediaPlayer` in the native renderer. This is the Android platform built-in way of playing videos. It could be possible that a particular manufacturer may have removed or customized parts of Android.

https://developer.android.com/reference/android/media/MediaPlayer
