### ISSUE TITLE
On Android Platform Full Screen Button

### ISSUE THREAD

**Issue by ercev** [adamfisher/Xamarin.Forms.VideoPlayer#140]
Hi,

there is no full screen button in android project. there is only play-pause , rewind and forward. i try to add display controls but didn't work. so i can't make it full screen on android. iOS is ok. with the same code.

`   <o:VideoPlayer Grid.Row="0" 
                               HorizontalOptions="FillAndExpand" 
                               VerticalOptions="FillAndExpand" 
                               DisplayControls="true"
                               x:Name="livePlayer"/>`

**Comment by adamfisher** [comment]
Duplicate of #37
