### ISSUE TITLE
Doesn't work with latest Visual Studio Build Settings

### ISSUE THREAD

**Issue by kenneymyers** [adamfisher/Xamarin.Forms.VideoPlayer#144]
I cannot install the nuget package into the shared project because it doesn't seem to be compatible with any of the PCL or .Net Standard profiles that are currently available.  Can you please provide the information in your getting started on what build settings you require?  Thank you!

UPDATE:
So it apparently requires us to use .net standard 1.4 - Will this be updated any time soon?  I have other packages that need to be more current.  Thanks again!

**Comment by adamfisher** [comment]
The shared library uses .NET Standard which is the default template for new Xamarin Forms projects currently.

.NET standard has an additive versioning system, meaning that each new version contains all the APIs of the previous versions, which makes it backwards compatible. And there never are any breaking changes between versions. So you should be fine to upgrade your project to a later version of .NET standard. The goal was to target as earlier a version of .NET standard as possible to provide the broadest support across all versions of .NET standard.
