### ISSUE TITLE
Can not stream from an IP Camera

### ISSUE THREAD

**Issue by amirnasser** [adamfisher/Xamarin.Forms.VideoPlayer#146]
I am trying to connect VideoPlayer via RTSP Protocol to an IP Camera and it failed. Is it because I am using Trial version ?

**Comment by adamfisher** [comment]
No the trial version shouldn't make a difference in this regard. You may need to look into the documentation of the specific platform you are working on to see what the requirements are for streaming  video. I know some have had success with RTSP on Android. This component simply wraps the default/native video player of each platform (iOS - AVPlayerViewController, Android - MediaPlayer, UWP - MediaElement) so it should just be a matter of passing in the URL in the format the platform expects, You can always create a custom renderer to extend `VideoPlayerRenderer` in your platform-specific projects.

**Comment by amirnasser** [comment]
OK, thanks for reply.
