### ISSUE TITLE
.Netstandard

### ISSUE THREAD

**Issue by AlenToma** [adamfisher/Xamarin.Forms.VideoPlayer#148]
is there a support for .netstandard and also is it able to play youtube videos
like this one for example 
https://www.youtube.com/watch?v=87Qtdh-jLi8
I already have integrated thair api but thair player dose not support autoplay on mobile.

so i really need this play for my new app.

**Comment by adamfisher** [comment]
There is an unofficial markup extension in the Chill Player example repo to grab the raw video URL YouTube is using under the hood but ideally you will want to use URLs you get from the YouTube API as you have mentioned.

https://github.com/adamfisher/Xamarin.Forms.VideoPlayer/blob/master/ChillPlayer/ChillPlayer/MarkupExtensions/YouTubeVideoIdExtension.cs
