### ISSUE TITLE
How to reduce the TimeElapsed interval?

### ISSUE THREAD

**Issue by EmmanuelJego** [adamfisher/Xamarin.Forms.VideoPlayer#149]
Hello!

I would like to display a progress bar under a video using your component.
I can use the TimeElapsed event handler, but the TimeElaspedInterval is an integer, so the minimum interval that I can set is 1 second, and I would like it to be more frequently called (each 0.1 second for instance).

I wanted to check if a native property could help, in the renderers. For Android, the Control has indeed a TimeElapsedInterval property which is a double, so I can set it at 0.1 second. However for iOS I can't find such a property.

Is there any way ?

Also, I noticed that on a Android 6.0 device, the TimeElapsed event handler isn't called anymore when the video restarts (with Repeat="True").

Thanks!
Emmanuel 

PS: I'm using the trial version.

**Comment by adamfisher** [comment]
Unfortunately Android didn't have a time elapsed interval event by default and I had to build it custom for that platform to match the others. I ended up using a timer object to keep track of when to fire the event and had to extend both my `VideoPlayerRenderer` and also Android's `MediaPlayer` to support what I needed to accomplish this. You could extend `VideoPlayerRenderer` and add a timer that supports fractional seconds but an easier approach to try first might be to just stay in the cross-platform project, add a timer there and set it to start and stop when the Playing/Paused/Completed events occur.
