### ISSUE TITLE
Where do I get a license key?

### ISSUE THREAD

**Issue by devBJ** [adamfisher/Xamarin.Forms.VideoPlayer#15]
Hi, what is needed from my ios application for create a valid License Key? In video (https://www.youtube.com/watch?v=JJ8NuGe_Fr8) I hear - manifest package id?﻿

**Comment by adamfisher** [comment]
1. You can [buy it here](https://components.xamarin.com/view/video-player).
2. Then follow the [Getting Started](https://components.xamarin.com/gettingstarted/video-player) guide to request your license key. It's based off the bundle ID you plan to deploy with to the app stores.
