### ISSUE TITLE
UIScreen.MainScreen.Capture() get black image

### ISSUE THREAD

**Issue by ShoWerZen** [adamfisher/Xamarin.Forms.VideoPlayer#150]
I want to get video capture image.
I use DependencyService to call my ios Capture method below

```
public class ScreenshotService : IScreenshotService
    {

        public byte[] Capture(VideoPlayer videoPlayer)
        {
            var capture = UIScreen.MainScreen.Capture();

            using (NSData data = capture.AsJPEG())
            {
                var bytes = new byte[data.Length];
                Marshal.Copy(data.Bytes, bytes, 0, Convert.ToInt32(data.Length));
                return bytes;
            }
        }
    }
```
Then:
var img = ImageSource.FromStream(() => new MemoryStream(screenshotData));

In the image, my video player is a black area.
Is there any solution I can do?

**Comment by adamfisher** [comment]
This component uses `AVPlayerViewController` on the native side. You might want to look into creating a Xamarin Forms custom renderer in your iOS project that extends `VideoPlayerRenderer` and maybe reusing some of the code from this StackOverflow link to make the video player capture the screenshot.

https://stackoverflow.com/questions/37225058/taking-screenshot-of-avplayer-but-it-works-for-some-videos

**Comment by ShoWerZen** [comment]
@adamfisher Thanks for your reply.
So I need to create a VideoPlayerRenderer and add a method to do the screenshot.
How can I invoke that method from pcl?
