### ISSUE TITLE
Seek not work with m3u8 video

### ISSUE THREAD

**Issue by ShoWerZen** [adamfisher/Xamarin.Forms.VideoPlayer#151]
I play a Hls m3u8 file.
And I want to seek the video to next part.
My code:

`int seekTime = playingPart.Position.Subtract(videoPlayer.CurrentTime).Seconds;
videoPlayer.Seek(seekTime);`

seekTime is 25
But the video didn't seek forward.

**Comment by adamfisher** [comment]
Seek time is the amount of time you want to move forward in the playback stream (i.e. it is not a timeline position). So specifying 25 should increase the playback position by 25 seconds from its current time. The ability to seek on a m3u8 file is also determined by the compatibility of `MediaPlayer` on Android and `AVPlayerViewController` on iOS (the native video player used on each platform).
