### ISSUE TITLE
Which formats supported ?

### ISSUE THREAD

**Issue by dhpanteon** [adamfisher/Xamarin.Forms.VideoPlayer#152]
1) Which formats are supported by this lib for android and ios platform? (e.x. mpeg, ogg, webm, mkv, flv.. ) have you implement different codecs ?
2) Is 4k video is supported ? or what is the max capacity of video resolution to play?

**Comment by adamfisher** [comment]
Android uses the `MediaPlayer` and iOS uses the `AVPlayerViewController` so you will want to refer to the documentation for those respective native platform controls to get more details specifically related to the versions you are targeting since they may have changed over time.
