### ISSUE TITLE
video/webm from API

### ISSUE THREAD

**Issue by francoisdutoit** [adamfisher/Xamarin.Forms.VideoPlayer#157]
How would i go about streaming a live 'video/webm' stream that is returend via an api?

I'm getting the stream from  example 'http://thevideodomain/api/video' and want the player to show the content.

Does it support this option?

Thanks!

**Comment by adamfisher** [comment]
`VideoSource.FromStream` may help as mentioned in #32

**Comment by francoisdutoit** [comment]
Hi @adamfisher, Thanks for the response. 

Below is what my code looks like at the moment - I have tested my stream in a browser and it is working I am however just seeing a black screen in my xamarin app. I have build my functionality into the sample ChillPlayer App - the YouTube and Vimeo videos work as expected.

    case VideoType.WebM:
    var streamer = new KinesisVideoStreamer();
    Func<Stream> streamFunctionPointer = streamer.StreamIt;
    VideoPlayer.Source = VideoSource.FromStream(streamFunctionPointer, "webm");
    break;

Any Ideas?

Thanks!

**Comment by francoisdutoit** [comment]
I have updated my code ...having looked at #32 but still not getting any video to dsiplay. Below are examples of my new code as well as the response message that I'm dealing with.

![image](https://user-images.githubusercontent.com/9386768/52227390-0b49f300-28b8-11e9-85d1-265d3b1f8238.png)

       case VideoType.WebM:
         var byteArray =  GetByteArray();
         VideoSource.FromStream(() => { return new MemoryStream(byteArray); }, "video/webm");
         break;

        public  byte[] GetByteArray()
        {
            const string URL = "http://localhost:49980/api/video/";
            var client = new HttpClient();
            client.BaseAddress = new Uri(URL);
            var response = client.GetAsync("").Result;
            return response.Content.ReadAsByteArrayAsync().Result;
        }

PS: Really want to buy a license - just want to know that it will work :) 
Thanks!

**Comment by adamfisher** [comment]
Use *webm* for the second parameter. It is the file extension name:
`VideoSource.FromStream(() => { return new MemoryStream(byteArray); }, "webm");`

**Comment by francoisdutoit** [comment]
@adamfisher  - That is what I had tried initially ....
