### ISSUE TITLE
Need Clraficaition

### ISSUE THREAD

**Issue by lumisoftusa** [adamfisher/Xamarin.Forms.VideoPlayer#159]
Hi,

I am loving the control  its pretty awesome event i can natively play youtube videos.
Great Job!

My only concser is i saw in the demos that you are calling "get_video_info" to get the youtube URL ,
I just wanted to know is this legal.

Regards

**Comment by adamfisher** [comment]
Thank you. That is for demo purposes only. If you are planning to stream videos from YouTube, you should use their official API. This is stated in the Getting Started documentation as well.
