### ISSUE TITLE
Are APK Expansion Files Supported?

### ISSUE THREAD

**Issue by Psercom** [adamfisher/Xamarin.Forms.VideoPlayer#16]
We like and appreciate your player but before we commit we are wondering if it supports playing media from APK expansion files on Android.  Or would we have to extend the code?  Perhaps there is sample code available somewhere since this would seem to be a common and important need for any real app.
Thanks.

**Comment by adamfisher** [comment]
I don't have direct experience with APK expansion but sounds possible. Here's a relevant snippet from the [APK Expansion Files](https://developer.android.com/google/play/expansion-files.html) documentation:

> If you're packaging media files into a ZIP, you can use media playback calls on the files with offset and length controls (such as MediaPlayer.setDataSource() and SoundPool.load()) without the need to unpack your ZIP. In order for this to work, you must not perform additional compression on the media files when creating the ZIP packages. For example, when using the zip tool, you should use the -n option to specify the file suffixes that should not be compressed: 
> zip -n .mp4;.ogg main_expansion media_files

Under the hood, this component uses Android's VideoView so worst case, you would create a custom renderer to extend and call `setDataSource()` for this scenario. Of course the easiest thing to do is just install the free trial nuget package and see if it suites your needs :-)

You are able to assign a source to `VideoPlayer.Source=""` from an embedded resource or a local/remote file path.

**Comment by Psercom** [comment]
Thanks Adam,

Yes, we are working with your free trial and have come quite far.

On this, it isn't clear setDataSource is available to be extended and 
called.  If this is right it seems to mean one can't use APK files at 
least directly because there's no way of addressing the position of the 
desired media file inside the APK zipand we are under the impression 
that's the canonical way to use them.

If you come across a code snippet starting in a direction around this 
we'd be most interested and appreciative.

Thanks much again.  Your code does so much if we can just get this going 
to make a deliverable app.
