### ISSUE TITLE
How I can Play and Pause  video from c# code.

### ISSUE THREAD

**Issue by sufyan-ahmad** [adamfisher/Xamarin.Forms.VideoPlayer#163]
How I can Play and Pause  video from c# code. Please help me I have added a button on play screen for some custom things. I want to pause video while doing custom things and play back video after custom code runs. please help me

**Comment by adamfisher** [comment]
You can respond to different player events by hooking into the `PlayerStateChanged` event and listening for specific actions. When a specific action occurs you can perform operations on the player.

https://github.com/adamfisher/Xamarin.Forms.VideoPlayer/blob/master/GettingStarted.md#playback-events
