### ISSUE TITLE
license key issue

### ISSUE THREAD

**Issue by rex232** [adamfisher/Xamarin.Forms.VideoPlayer#166]
Hi I was purchased the component for a long time and now i re-pick it to use. The  project have been changed the bundle id and how should i renew the license key? thanks

**Comment by adamfisher** [comment]
So it is the same mobile application as before but you are only changing the bundle ID? If so, please reply to your original license key email with the new bundle ID and I can get this adjusted.

However, if it is a completely new app, you will need to repurchase using the PayPal link on the home page of this repo.
