### ISSUE TITLE
FormsVideoPlayer.Init() not found in version 3.0

### ISSUE THREAD

**Issue by khairnar** [adamfisher/Xamarin.Forms.VideoPlayer#168]
FormsVideoPlayer.Init() not found in version 3.0, hence we must remove that line from native code which result in failure of loading and playing videos

**Comment by adamfisher** [comment]
Correct. You should now call it without passing the key.

**Comment by khairnar** [comment]
I didn't get. please give code example.

when i type FormsVideoPlayer.Init() in Android or iOS project, i get compile time error.
