### ISSUE TITLE
Can we embed ffmpeg library

### ISSUE THREAD

**Issue by dnyandeep** [adamfisher/Xamarin.Forms.VideoPlayer#17]
Hi Adam,

Is it possible to add ffpemg library to the video player to play all types of codec ?

Regards,
Dnyandeep

**Comment by adamfisher** [comment]
If you are able to embed ffmpeg as a Xamarin binding library and then pass the resulting stream via file system path or as a `Stream` object I don't see why not. The challenge is actually running ffmpeg on a mobile device and binding libraries are not easy to create. Plus it would be best to encode video remotely on a server as it could be a real drain to the user's battery.
