### ISSUE TITLE
Video not playing for API 28 android.

### ISSUE THREAD

**Issue by kishor010** [adamfisher/Xamarin.Forms.VideoPlayer#175]
I tried with the two video
    http://devimages.apple.com/iphone/samples/bipbop/bipbopall.m3u8
**App is targeting API 28.**
It is working for API 27.
But it is not working for API 28.
Is it not updated for API 28 ?

**Comment by adamfisher** [comment]
What error are you receiving?

**Comment by kishor010** [comment]
@adamfisher 
I getting this below error :

**Couldn't open http://vjs.zencdn.net/v/oceans.mp4: java.io.FileNotFoundException**: No content provider: http://vjs.zencdn.net/v/oceans.mp4

**Comment by kishor010** [comment]
@adamfisher 
What I assume is from API Level 28 
http web content will not play and https is working fine.

**Comment by Tmaturano** [comment]
@adamfisher I could simulate the issue in Android 9 (API 28), the screen is black, even if I touch to show the controls, nothing happens.
Works fine for APIs under 28

The error is: **Couldn't open http://vjs.zencdn.net/v/oceans.mp4: java.io.FileNotFoundException: No content provider: http://vjs.zencdn.net/v/oceans.mp4**

**Comment by adamfisher** [comment]
Please see the following query for related issues:

https://github.com/adamfisher/Xamarin.Forms.VideoPlayer/issues?utf8=%E2%9C%93&q=No+content+provider
