### ISSUE TITLE
When can we get new SDK with solution of Android aspect ratio?

### ISSUE THREAD

**Issue by kishor010** [adamfisher/Xamarin.Forms.VideoPlayer#176]
We are facing issue with content mode for android.
It is not updating and only taking AspectFill mode.

**Comment by mpsarannyaCharu** [comment]
Even am also facing same issue..pls let me know the solution.

**Comment by adamfisher** [comment]
Unfortunately, this has not seen a solution since issue #3 but if anyone wants to take a look at the code since open sourcing, someone may have ideas :-)
