### ISSUE TITLE
Master unlock key for older versions

### ISSUE THREAD

**Issue by JKennedy24** [adamfisher/Xamarin.Forms.VideoPlayer#178]
I am using version 2.2.0 because of an issue with the latest version
https://github.com/adamfisher/Xamarin.Forms.VideoPlayer/issues/170

Therefore I was wondering if it would be possible to get a master unlock key to be able to use older versions - prior to it being open sourced

**Comment by adamfisher** [comment]
The code for the licensing does not have a master key. It is computed directly from the bundle ID of your app. At least now you should be able to see the internals of different classes for the purpose of extending/overriding a specific behavior.

**Comment by JKennedy24** [comment]
I had a quick look at the source and couldnt see anywhere where a licence key was being validated. I'm guessing this has been removed in the latest version? I was going to reverse engineer the licencing to generate my own key.

At the moment I am stuck on version 2.2.0 but with no licence so after 15 seconds an exception is thrown.

Is there any way to overcome this without pulling the source code into my project?
