### ISSUE TITLE
Doesn't compatible with target Android Version 9.0

### ISSUE THREAD

**Issue by Jmunozg** [adamfisher/Xamarin.Forms.VideoPlayer#179]
In the target Android version 9.0 Api Level 28, The video doesn't play when is an url. Please solve this issues.

**Comment by DPY81** [comment]
I think I'm having the same too, still digging into it

**Comment by DPY81** [comment]
Found the problem … maybe Android 9.0 security related.  When the URL is http:// then the file will not load in the player.  When the URL is https:// then all will be OK.

**Comment by Jmunozg** [comment]
Thanks bro.

**Comment by DPY81** [comment]
> Thanks bro.

You're welcome
