### ISSUE TITLE
I need to playback encrypted video file with this player

### ISSUE THREAD

**Issue by sameerdube9** [adamfisher/Xamarin.Forms.VideoPlayer#18]
Hi Adam,

I am looking forward to have cross platform solution to playback video from decrypted stream chunk by chunk from encrypted video file (.mp4)

How can i achieve this with your cross platform player?

**Comment by adamfisher** [comment]
You should be able to try out the `VideoSource.FromStream(...)` method to pass a raw `Stream` object.

```csharp
/// <summary>
/// Returns a new <see cref="T:Xamarin.Forms.StreamVideoSource" /> that reads from <paramref name="stream" />.
/// </summary>
/// <param name="stream">The lambda responsible for extracting the stream.</param>
/// <param name="format">The stream container format (i.e. "mp4", "webm", etc.)</param>
/// <returns></returns>
public static VideoSource FromStream(Func<Stream> stream, string format);
```

**Comment by NPC-CPT** [comment]
Could you elaborate on this?

I've tried making a custom stream that works to feed it the encrypted pieces. However the player just consumes the entire contents of the array from stream before starting. I'd like a methodology to not reading the entire file, the file size is large enough that decrypting the entire array takes much too long.
