### ISSUE TITLE
RTSP or RTMP Support?

### ISSUE THREAD

**Issue by windsql** [adamfisher/Xamarin.Forms.VideoPlayer#19]
I'm looking for real-time video player program by H.264. Does your program provide the RTSP or RTMP?

**Comment by adamfisher** [comment]
I just tested an RTSP URL on the Android Chill Player example app that is packaged with the component on the Xamarin Component Store and it works! So yes, RTSP does appear to be supported for Android.

[rtsp://184.72.239.149/vod/mp4:BigBuckBunny_115k.mov](rtsp://184.72.239.149/vod/mp4:BigBuckBunny_115k.mov)

iOS is a different animal and does not appear to support either format although this could change in the future. I would recommend you look into HLS streams, as they are supported on both iOS and Android natively. You can test out your streams using the example app mentioned above with the trial version of the player to make sure everything is how you want it before purchasing.
