### ISSUE TITLE
CurrentTime is unreliable on UWP

### ISSUE THREAD

**Issue by charlesroddie** [adamfisher/Xamarin.Forms.VideoPlayer#2]
At the moment on UWP ```.CurrentTime``` is unreliable. If you seek using the slider, or if you seek using ```.Seek() ```,  ```.CurrentTime``` doesn't immediately change. It doesn't change until the player starts playing; then after a second it gets updated.

It is possible this is related to https://bitbucket.org/OctaneSoftware/octane.xam.videoplayer/issues/24/seek-command-jumps-large-intervals-when

Also related to https://bitbucket.org/OctaneSoftware/octane.xam.videoplayer/issues/41/make-currenttime-to-be-seekable in that the only way currently to seek to an absolute time is to get ```.CurrentTime```.

**Comment by adamfisher** [comment]
Yes it is related to that. The current time property has a refresh rate of one second. This limitation is not something that be easily addressed as one of the challenges of unifying all platform players to update a single CurrentTime property in a consistent manner.

**Comment by charlesroddie** [comment]
Do you think a settable currenttime property looks feasible?

**Comment by charlesroddie** [comment]
@adamfisher Unreliable CurrentTime is a major issue. Dont' know why this issue is closed since it has not been fixed.

I'd be very surprised if native players did not expose something equivalent. It sounds like you are updating a mutable variable and getting that, rather than getting the property from the native player. Why not get it from the native player? Is there a platform where such a property is not exposed?
