### ISSUE TITLE
Not able to compile ChillPlayer

### ISSUE THREAD

**Issue by iscisse** [adamfisher/Xamarin.Forms.VideoPlayer#20]
Hello,
Everytime i compile the solution I get the following error:

Failed to resolve all project references for 'ChillPlayer.UWP'. The package restore result for 'C:\Users\icisse\Downloads\video-player-1.2.3-trial\video-player-1.2.3\samples\ChillPlayer\ChillPlayer.UWP\ChillPlayer.UWP.csproj' may be incomplete.
Restoring NuGet packages...
To prevent NuGet from restoring packages during build, open the Visual Studio Options dialog, click on the Package Manager node and uncheck 'Allow NuGet to download missing packages during build.'
1>------ Rebuild All started: Project: ChillPlayer, Configuration: Debug Any CPU ------
1>  ChillPlayer -> C:\Users\icisse\Downloads\video-player-1.2.3-trial\video-player-1.2.3\samples\ChillPlayer\ChillPlayer\bin\Debug\ChillPlayer.dll
2>------ Rebuild All started: Project: ChillPlayer.Android, Configuration: Debug Any CPU ------
3>------ Rebuild All started: Project: ChillPlayer.iOS, Configuration: Debug iPhone ------
4>------ Rebuild All started: Project: ChillPlayer.WinPhone, Configuration: Debug Any CPU ------
5>------ Rebuild All started: Project: ChillPlayer.UWP, Configuration: Debug x86 ------
4>C:\Program Files (x86)\MSBuild\14.0\bin\Microsoft.Common.CurrentVersion.targets(1611,5): warning : The referenced project '..\..\src\Octane.Xam.VideoPlayer\Octane.Xam.VideoPlayer.csproj' does not exist.
4>C:\Users\icisse\Downloads\video-player-1.2.3-trial\video-player-1.2.3\samples\ChillPlayer\ChillPlayer.WinPhone\App.xaml.cs(6,7,6,13): error CS0246: The type or namespace name 'Octane' could not be found (are you missing a using directive or an assembly reference?)
3>C:\Program Files (x86)\MSBuild\Xamarin\iOS\Xamarin.iOS.Windows.After.targets(63,5): warning VSX1000: No Address and User has been specified in order to establish a connection to a Mac Server, so only the main assembly was compiled for project 'ChillPlayer.iOS'. Connect to a Mac Server and try again to build the full application.
3>C:\Program Files (x86)\MSBuild\Xamarin\iOS\Xamarin.iOS.Common.targets(1103,3): warning : There is no available connection to the Mac, hence the task Xamarin.MacDev.Tasks.CollectBundleResources will not be executed
3>C:\Users\icisse\Downloads\video-player-1.2.3-trial\video-player-1.2.3\samples\ChillPlayer\packages\Microsoft.Bcl.Build.1.0.21\build\Microsoft.Bcl.Build.targets(243,5): warning : Project must install nuget package Microsoft.Bcl, version=1.1.10. For more information, see http://go.microsoft.com/fwlink/?LinkID=317570.
3>C:\Users\icisse\Downloads\video-player-1.2.3-trial\video-player-1.2.3\samples\ChillPlayer\packages\Microsoft.Bcl.Build.1.0.21\build\Microsoft.Bcl.Build.targets(243,5): warning : Project must install nuget package Microsoft.Net.Http, version=2.2.29. For more information, see http://go.microsoft.com/fwlink/?LinkID=317570.
3>  No way to resolve conflict between "System.Xml, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089" and "System.Xml, Version=2.0.5.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e". Choosing "System.Xml, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089" arbitrarily.
3>  Consider app.config remapping of assembly "System.Runtime, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a" from Version "1.5.11.0" [] to Version "4.0.0.0" [C:\WINDOWS\Microsoft.Net\assembly\GAC_MSIL\System.Runtime\v4.0_4.0.0.0__b03f5f7f11d50a3a\System.Runtime.dll] to solve conflict and get rid of warning.
3>  Consider app.config remapping of assembly "System.IO, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a" from Version "1.5.11.0" [] to Version "4.0.0.0" [C:\WINDOWS\Microsoft.Net\assembly\GAC_MSIL\System.IO\v4.0_4.0.0.0__b03f5f7f11d50a3a\System.IO.dll] to solve conflict and get rid of warning.
3>  Consider app.config remapping of assembly "System.Net.Http, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a" from Version "1.5.0.0" [C:\Users\icisse\Downloads\video-player-1.2.3-trial\video-player-1.2.3\samples\ChillPlayer\ChillPlayer\bin\Debug\System.Net.Http.dll] to Version "4.0.0.0" [C:\Program Files (x86)\Reference Assemblies\Microsoft\Framework\Xamarin.iOS\v1.0\System.Net.Http.dll] to solve conflict and get rid of warning.
3>  Consider app.config remapping of assembly "System.Threading.Tasks, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a" from Version "1.5.11.0" [] to Version "4.0.0.0" [C:\WINDOWS\Microsoft.Net\assembly\GAC_MSIL\System.Threading.Tasks\v4.0_4.0.0.0__b03f5f7f11d50a3a\System.Threading.Tasks.dll] to solve conflict and get rid of warning.
3>C:\Program Files (x86)\MSBuild\14.0\bin\Microsoft.Common.CurrentVersion.targets(1820,5): warning MSB3276: Found conflicts between different versions of the same dependent assembly. Please set the "AutoGenerateBindingRedirects" property to true in the project file. For more information, see http://go.microsoft.com/fwlink/?LinkId=294190.
3>  ChillPlayer.iOS -> C:\Users\icisse\Downloads\video-player-1.2.3-trial\video-player-1.2.3\samples\ChillPlayer\ChillPlayer.iOS\bin\iPhone\Debug\ChillPlayeriOS.exe
5>C:\Users\icisse\Downloads\video-player-1.2.3-trial\video-player-1.2.3\samples\ChillPlayer\packages\Microsoft.Bcl.Build.1.0.21\build\Microsoft.Bcl.Build.targets(243,5): warning : Project must install nuget package Microsoft.Net.Http, version=2.2.29. For more information, see http://go.microsoft.com/fwlink/?LinkID=317570.
5>C:\Program Files (x86)\MSBuild\14.0\bin\Microsoft.Common.CurrentVersion.targets(1611,5): warning : The referenced project '..\..\src\Octane.Xam.VideoPlayer\Octane.Xam.VideoPlayer.csproj' does not exist.
5>C:\Users\icisse\Downloads\video-player-1.2.3-trial\video-player-1.2.3\samples\ChillPlayer\ChillPlayer.UWP\App.xaml.cs(6,7,6,13): error CS0246: The type or namespace name 'Octane' could not be found (are you missing a using directive or an assembly reference?)
2>C:\Users\icisse\Downloads\video-player-1.2.3-trial\video-player-1.2.3\samples\ChillPlayer\packages\Microsoft.Bcl.Build.1.0.21\build\Microsoft.Bcl.Build.targets(243,5): warning : Project must install nuget package Microsoft.Bcl, version=1.1.10. For more information, see http://go.microsoft.com/fwlink/?LinkID=317570.
2>C:\Users\icisse\Downloads\video-player-1.2.3-trial\video-player-1.2.3\samples\ChillPlayer\packages\Microsoft.Bcl.Build.1.0.21\build\Microsoft.Bcl.Build.targets(243,5): warning : Project must install nuget package Microsoft.Net.Http, version=2.2.29. For more information, see http://go.microsoft.com/fwlink/?LinkID=317570.
2>  Consider app.config remapping of assembly "System.Runtime, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a" from Version "4.0.0.0" [] to Version "4.1.0.0" [C:\Program Files (x86)\Reference Assemblies\Microsoft\Framework\MonoAndroid\v1.0\Facades\System.Runtime.dll] to solve conflict and get rid of warning.
2>  Consider app.config remapping of assembly "System.IO, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a" from Version "1.5.11.0" [] to Version "4.0.0.0" [] to solve conflict and get rid of warning.
2>  Consider app.config remapping of assembly "System.Net.Http, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a" from Version "1.5.0.0" [C:\Users\icisse\Downloads\video-player-1.2.3-trial\video-player-1.2.3\samples\ChillPlayer\ChillPlayer\bin\Debug\System.Net.Http.dll] to Version "4.0.0.0" [C:\Program Files (x86)\Reference Assemblies\Microsoft\Framework\MonoAndroid\v1.0\System.Net.Http.dll] to solve conflict and get rid of warning.
2>  Consider app.config remapping of assembly "System.Threading.Tasks, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a" from Version "1.5.11.0" [] to Version "4.0.0.0" [] to solve conflict and get rid of warning.
2>C:\Program Files (x86)\MSBuild\14.0\bin\Microsoft.Common.CurrentVersion.targets(1820,5): warning MSB3247: Found conflicts between different versions of the same dependent assembly. In Visual Studio, double-click this warning (or select it and press Enter) to fix the conflicts; otherwise, add the following binding redirects to the "runtime" node in the application configuration file: <assemblyBinding xmlns="urn:schemas-microsoft-com:asm.v1"><dependentAssembly><assemblyIdentity name="System.Runtime" culture="neutral" publicKeyToken="b03f5f7f11d50a3a" /><bindingRedirect oldVersion="0.0.0.0-4.1.0.0" newVersion="4.1.0.0" /></dependentAssembly></assemblyBinding><assemblyBinding xmlns="urn:schemas-microsoft-com:asm.v1"><dependentAssembly><assemblyIdentity name="System.IO" culture="neutral" publicKeyToken="b03f5f7f11d50a3a" /><bindingRedirect oldVersion="0.0.0.0-4.0.0.0" newVersion="4.0.0.0" /></dependentAssembly></assemblyBinding><assemblyBinding xmlns="urn:schemas-microsoft-com:asm.v1"><dependentAssembly><assemblyIdentity name="System.Net.Http" culture="neutral" publicKeyToken="b03f5f7f11d50a3a" /><bindingRedirect oldVersion="0.0.0.0-4.0.0.0" newVersion="4.0.0.0" /></dependentAssembly></assemblyBinding><assemblyBinding xmlns="urn:schemas-microsoft-com:asm.v1"><dependentAssembly><assemblyIdentity name="System.Threading.Tasks" culture="neutral" publicKeyToken="b03f5f7f11d50a3a" /><bindingRedirect oldVersion="0.0.0.0-4.0.0.0" newVersion="4.0.0.0" /></dependentAssembly></assemblyBinding>
2>    Processing: obj\Debug\res\values\styles.xml
2>    Processing: C:\Users\icisse\Downloads\video-player-1.2.3-trial\video-player-1.2.3\samples\ChillPlayer\ChillPlayer.Android\obj\Debug\__library_projects__\Octane.Xam.VideoPlayer.Android\library_project_imports\res\values\strings.xml
2>  ChillPlayer.Android -> C:\Users\icisse\Downloads\video-player-1.2.3-trial\video-player-1.2.3\samples\ChillPlayer\ChillPlayer.Android\bin\Debug\ChillPlayer.Android.dll
2>  Consider app.config remapping of assembly "System.Runtime, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a" from Version "1.5.11.0" [] to Version "4.0.0.0" [] to solve conflict and get rid of warning.
2>  Consider app.config remapping of assembly "System.IO, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a" from Version "1.5.11.0" [] to Version "4.0.0.0" [] to solve conflict and get rid of warning.
2>  Consider app.config remapping of assembly "System.Net.Http, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a" from Version "1.5.0.0" [C:\Users\icisse\Downloads\video-player-1.2.3-trial\video-player-1.2.3\samples\ChillPlayer\ChillPlayer\bin\Debug\System.Net.Http.dll] to Version "4.0.0.0" [C:\Program Files (x86)\Reference Assemblies\Microsoft\Framework\MonoAndroid\v1.0\System.Net.Http.dll] to solve conflict and get rid of warning.
2>  Consider app.config remapping of assembly "System.Threading.Tasks, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a" from Version "1.5.11.0" [] to Version "4.0.0.0" [] to solve conflict and get rid of warning.
2>C:\Program Files (x86)\MSBuild\Xamarin\Android\Xamarin.Android.Common.targets(2125,3): warning MSB3247: Found conflicts between different versions of the same dependent assembly. In Visual Studio, double-click this warning (or select it and press Enter) to fix the conflicts; otherwise, add the following binding redirects to the "runtime" node in the application configuration file: <assemblyBinding xmlns="urn:schemas-microsoft-com:asm.v1"><dependentAssembly><assemblyIdentity name="System.Runtime" culture="neutral" publicKeyToken="b03f5f7f11d50a3a" /><bindingRedirect oldVersion="0.0.0.0-4.0.0.0" newVersion="4.0.0.0" /></dependentAssembly></assemblyBinding><assemblyBinding xmlns="urn:schemas-microsoft-com:asm.v1"><dependentAssembly><assemblyIdentity name="System.IO" culture="neutral" publicKeyToken="b03f5f7f11d50a3a" /><bindingRedirect oldVersion="0.0.0.0-4.0.0.0" newVersion="4.0.0.0" /></dependentAssembly></assemblyBinding><assemblyBinding xmlns="urn:schemas-microsoft-com:asm.v1"><dependentAssembly><assemblyIdentity name="System.Net.Http" culture="neutral" publicKeyToken="b03f5f7f11d50a3a" /><bindingRedirect oldVersion="0.0.0.0-4.0.0.0" newVersion="4.0.0.0" /></dependentAssembly></assemblyBinding><assemblyBinding xmlns="urn:schemas-microsoft-com:asm.v1"><dependentAssembly><assemblyIdentity name="System.Threading.Tasks" culture="neutral" publicKeyToken="b03f5f7f11d50a3a" /><bindingRedirect oldVersion="0.0.0.0-4.0.0.0" newVersion="4.0.0.0" /></dependentAssembly></assemblyBinding>
2>    Processing: obj\Debug\res\values\styles.xml
2>    Processing: obj\Debug\res\values\styles.xml
2>    Processing: C:\Users\icisse\Downloads\video-player-1.2.3-trial\video-player-1.2.3\samples\ChillPlayer\ChillPlayer.Android\obj\Debug\__library_projects__\Octane.Xam.VideoPlayer.Android\library_project_imports\res\values\strings.xml
========== Rebuild All: 3 succeeded, 2 failed, 0 skipped ==========

**Comment by adamfisher** [comment]
You will want to make sure you have a connection to a Mac build agent to build the iOS version. Beyond that, this looks like "nuget restore hell". You may need to uninstall and reinstall the nuget packages in the solution. Specifically the Xamarin.Forms packages.

**Comment by iscisse** [comment]
Hello,
i was able to connect it to MAC, but now I am getting the following errors:

Severity Code Description Project File Line Suppression State
Error CS0246 The type or namespace name 'Octane' could not be found (are
you missing a using directive or an assembly reference?) ChillPlayer.UWP
C:\Users\icisse\Downloads\video-player-1.2.3-trial\video-player-1.2.3\samples\ChillPlayer\ChillPlayer.UWP\App.xaml.cs
6 Active

Severity Code Description Project File Line Suppression State
Error CS0103 The name 'FormsVideoPlayer' does not exist in the current
context ChillPlayer.UWP
C:\Users\icisse\Downloads\video-player-1.2.3-trial\video-player-1.2.3\samples\ChillPlayer\ChillPlayer.UWP\App.xaml.cs
53 Active

I am still trying to fix these issue.
Thanks..

**Comment by adamfisher** [comment]
This sounds more like an issue with nuget restore than the component. Try right clicking on the `References` node in the project and manually select the path to the DLL file in the nuget packages folder. This should at least let you run the sample. Do you experience the same problems restoring nuget in Xamarin Studio on the Mac?
