### ISSUE TITLE
Error iOS playing video mp4 from https

### ISSUE THREAD

**Issue by ghost** [adamfisher/Xamarin.Forms.VideoPlayer#25]
Hi Adam,

I’m getting issues when trying to play videos.

I can listen but I can’t watch them.

Videos’ format: mp4 from https

Xaml:
```
<StackLayout HorizontalOptions="FillAndExpand">
  <o:VideoPlayer Source="{Binding}" 
                 AutoPlay="True" 
                 FillMode="ResizeAspect" 
                 VerticalOptions="CenterAndExpand" 
                 HorizontalOptions="CenterAndExpand" />
</StackLayout>
```

I already added to Info.plist the following configuration:

```
<key>NSAppTransportSecurity</key>
<dict>
  <key>NSAllowsArbitraryLoads</key>
  <true/>
</dict> 
```

Android version is playing them without any problems. 

What am I missing? 

Sincerely

**Comment by adamfisher** [comment]
That permission should only be necessary when trying to play non-HTTPS based streams. iOS 9+ restricts HTTP by default so that doesn't sound like your problem since you are attempting to play HTTPS. It really comes down to what `AVPlayer` supports. Are you able to play other URLs? Can you share the URL causing problems?

**Comment by ghost** [comment]
Still I'm not able to play any url in iOS.

I already include FormsVideoPlayer.Init("LICENSE_KEY"); after Xamarin.Forms.Forms.Init() in the AppDelegate.cs file.

In azure the content type of videos is application/octet-stream and I think it is not necessary to change to video/mp4 because Android version is already playing very well.

Officially AVPlayer supports mp4.

I need to play https but sometimes I must play http. In this case is enough with:
```
<key>NSAppTransportSecurity</key>
<dict>
  <key>NSAllowsArbitraryLoads</key>
  <true/>
</dict> 
```
or Do I must specify the domain configuration like?
```
<key>NSAppTransportSecurity</key>
<dict>
  <key>NSAllowsArbitraryLoads</key>
  <false/>
  <key>NSExceptionDomains</key>
  <dict>
    <key>somedomain.com</key>
    <dict>
      <key>NSIncludesSubdomains</key>
      <true/>
      <key>NSExceptionMinimumTLSVersion</key>
      <string>TLSv1.0</string>
    </dict>
  </dict>
</dict>

```

**Comment by adamfisher** [comment]
A quick review online looks like a lot of people have asked the same question about `AVPlayer` supporting **application/octet-stream** and no one answering any of them. I would give the `video/mp4` content type a try.

The specific domain configuration is ideal as I am not certain Apple will let you approve everything under a catch-all so the second one is better.
