### ISSUE TITLE
Audio streaming

### ISSUE THREAD

**Issue by fmeneuhe** [adamfisher/Xamarin.Forms.VideoPlayer#26]
Hi,
Does this plugin support audio streaming?
Thanks

**Comment by adamfisher** [comment]
I don't see any restrictions as most of the platforms use the same media object for both audio and video. Under the hood, this component uses the AVPlayer on iOS, the MediaPlayer on Android, and the MediaElement on Windows Phone so it comes down to the formats each of the platforms you wish to target will support. Easiest thing to do is plug in an audio URL in trial mode and see if you like what you see :-)
