### ISSUE TITLE
Providing databound video ids from Youtube or Vimeo to Markup Extensions

### ISSUE THREAD

**Issue by satputerohan** [adamfisher/Xamarin.Forms.VideoPlayer#27]
Hi Adam,
We bought the Video Player a few days back and I am trying to implement it in XAML to stream Youtube/Vimeo videos. In getting started page you mention the markup extension YouTubeVideoId:

Converts a YouTube video ID into a compatible stream URL for playback.
Example: <o:VideoPlayer Source="{e:YouTubeVideoId vu4WK-FMyIg }" />

Now, I have to databind the video id to a variable in my viewmodel (MVVM). So "vu4WK-FMyIg" in above example is a value provided by some variable "ytVideoID" in the viewmodel. I am unsure of how I can achieve this. Any suggestions?

P.S. - I went through the Chill Player implementation, which does this in the code behind on custom button events/commands. Is there any way to do this in XAML itself?

**Comment by satputerohan** [comment]
Nevermind. I ended up using a custom IValueConverter and using the markup extensions from there to get the video source.

**Comment by raf66** [comment]
Hello satputerohan,
Any chance you can share your IValueConverter solution?
