### ISSUE TITLE
anchoring default DisplayControls to the video.

### ISSUE THREAD

**Issue by satputerohan** [adamfisher/Xamarin.Forms.VideoPlayer#28]
Hello Adam,

I am trying to use the video player in a community feed (like facebook). All is working fine, but if I scroll the feed, the displaycontrols are not anchored to the video (I suspect it uses the absolute layout to draw controls). How can I set the anchor/fix it so that the controls scroll with the view.
Another thing is that I wanted to add a full screen option to the controller, which will render the video in landscape mode on demand. How can I achieve this? Is their a way that I can make changes to the default controls?

Thanks,
Rohan

![screenshot_1496046578](https://cloud.githubusercontent.com/assets/4294799/26542483/a81edf6e-4477-11e7-9405-4b5e6b31e3ea.png)

**Comment by adamfisher** [comment]
The Android implementation is using Android's `VideoView` which takes a `MediaController` that is responsible for the positioning of the player's controls. You should be able to extend `VideoPlayerRenderer` in your Android project and the corresponding `VideoView` control that it wraps to achieve the desired effects.

I don't have a lot of experience with the full screen aspect and would require searching for some different code snippets on some variation of "full screen Video View". The same goes for the positioning the controls over the player. A quick search yielded code similar to the below code that you would need to use in your custom renderer's VideoView:

```
MediaController controller = new MediaController(this);
controller.setAnchorView(this.videoView);
controller.setMediaPlayer(this.videoView);
this.videoView.setMediaController(controller);
```

**Comment by satputerohan** [comment]
I forgot to mention in my original post that I am working on a xamarin forms project. I have no clue about Android native development.
