### ISSUE TITLE
Crash at development stage

### ISSUE THREAD

**Issue by slava-osipov-qs** [adamfisher/Xamarin.Forms.VideoPlayer#30]
I'm developing Windows Store application and purchased VideoPlayer license.
I've added call of FormsVideoPlayer.Init(...) to appropriate place in app with actual license key, but now it always crashed with following stack trace:
at Windows.ApplicationModel.Store.CurrentApp.get_AppId()
 at Octane.Xam.VideoPlayer.WindowsStore.PlatformFeatures.get_PackageName()
  at Octane.Xam.VideoPlayer.Licensing.VideoPlayerLicense.Initialize(String licenseKey)
   at Octane.Xam.VideoPlayer.WindowsStore.FormsVideoPlayer.Init(String licenseKey)
.....
and HResult is 0x803F6107
Crash occur when I start my app from Visual Studio 2015 for debugging purposes.
Application target is Windows 8.1 and I'm run it on Windows 10.

Looking to the documentation of [CurrentApp](http://msdn.microsoft.com/en-us/library/windows/apps/windows.applicationmodel.store.currentapp) I can see that my application must be published in Windows Store to make this API working. But I'm at development stage and can't publish unfinished application! 
Any suggestions excluding removal of FormsVideoPlayer.Init(...) call?

**Comment by adamfisher** [comment]
Windows 8 has been temperamental. In the interim, I would recommend running in trial mode without specifying the key until you are ready to publish.
