### ISSUE TITLE
Video Player not working with live youtube videos.

### ISSUE THREAD

**Issue by marcel-silva** [adamfisher/Xamarin.Forms.VideoPlayer#31]
Sorry i've opened a ticket in bitbucket before i realize i was suppose to do it here.

anyway,
Is live youtube stream even supported by your video player?

I was digging into the chillplayer demo code, and it looks like "url_encoded_fmt_stream_map" is always empty with live videos.

I read online that we should use "hlsvp" parameter instead,
but i was unable to make the live video bind to the videoplayer.

appreciate any help.

thanks

**Comment by adamfisher** [comment]
There is nothing preventing you from streaming a video file from YouTube. The Chill Player shows a XAML markup extension that retrieves and parses the web page to get the correct URL for playback. That is obviously not an officially supported way of getting YouTube videos for your users but you are free to do it nonetheless. It's really just a matter of getting a valid stream URL for playback which is entirely up to the developer as to the URL you pass the player. Ideally you would do it through the YouTube API for a production mobile app. I'm sorry I am not familiar with their API but they do have streaming documentation [located here](https://developers.google.com/youtube/v3/live/getting-started).
