### ISSUE TITLE
Video Player not working when loading from the stream on Android Device only 

### ISSUE THREAD

**Issue by pengx** [adamfisher/Xamarin.Forms.VideoPlayer#32]
When loading from the stream,  Video player only works on iOS, and UWP, It does not work on Android.  Used real Android device (Samsung S8) for both local file and stream,  emulators for iOS and UWP.

Both methods have failed to load/play (no exception thrown though):
-------- 
VideoSource.FromStream(() => { return new MemoryStream(MyByte[]array); }, ".mp4");

or

StreamVideoSource.FromStream(() => { return new MemoryStream(MyByte[]array); }, ".mp4");
--------

**Comment by okhosting** [comment]
Hello,

We are having the same issue on an android 4.4.2 tablet, lenovo model 60046. We are using this online stream;

http://live10.cdnmedia.tv/udgmxlive/smil:canal44.smil/playlist.m3u8

You can see the source code in here:

https://github.com/okhosting/OKHOSTING.UDG/tree/master/src/TV

The exact same build works fine on Android 4.1 cellphones. Its just on the tablet that it does not load. Not even the play/pause controls get displayed.

Thanks in advance for your support.

Sincerily,
David

**Comment by okhosting** [comment]
I forgot to mention that iOS versions are working fine.

**Comment by adamfisher** [comment]
Try the file extension without the dot:

`VideoSource.FromStream(() => { return new MemoryStream(MyByte[]array); }, "mp4");`

**Comment by adamfisher** [comment]
Did that help?

**Comment by okhosting** [comment]
Not in my case, should I post a new question? I gues my case is different than OPs, do you have any updates for my scenario?

Thanks in advance

**Comment by habeebmatrix** [comment]
How can I set the YoutubeVideoId from code behind.

**Comment by pdougla002** [comment]
Hi Adam,
I'm seeing the same issue (error on loading a stream in Android, iOS works fine). I planned on getting a license if you're actively maintaining this. Please let me know! I was only using the trial version of course. Thanks!

**Comment by pengx** [comment]
I found out the issue was not related with code, but from the video encoder, you should make sure that encoding is compatible, not only the container.

**Comment by pdougla002** [comment]
Hi @pengx can you elaborate a bit? Are you saying that the encoding when creating the mp4 is causing the problem? Thanks

**Comment by pdougla002** [comment]
I understand now. I was able to download my video sample and run it through Handbrake to encode it H.264 (I don't know what it was before). I loaded the sample as a resource file and it played on both iPhone and Android.

**Comment by pdougla002** [comment]
Still having a problem with a web served mp4 using ChillPlayer sample on Android. The encoding on the file was changed to H.264. Local videos and the oceans.mp4 work fine, iOS works fine. I will send the file Url so you can hopefully let me know if the issue is with the file or something on your side.
Thanks!

**Comment by wass9085** [comment]
Cant figure out how to play a a video in xaml form a local source

**Comment by kasagga** [comment]
Cant figure out how to play a a video in xaml from a local source

**Comment by adamfisher** [comment]
Local source should use an Android file path which you may need to use a different plugin to get file system paths in a cross-platform manner unless you already know the path you should be able to just pass it right in. The exception is embedded resources in which case you should use `VideoSource.FromResource() method to assign the source`.
