### ISSUE TITLE
Problem loading Video from File on UWP

### ISSUE THREAD

**Issue by Graham-Bennett** [adamfisher/Xamarin.Forms.VideoPlayer#34]
**This code:**

var videoSource = VideoSource.FromFile("D:\\Videos\\snow.mp4");  
MainPageVideoPlayer.Source = videoSource;

**gives this error:** 

Error: Unsupported video type or invalid file path. 

**The video is your sample from Github.**

The videoplayer works fine with a Youtube Id.

**Comment by Graham-Bennett** [comment]
I can see that I will need to use a library such as PCLStorage and PCL Special Folder but I am not quite sure what to then pass to videoplayer to let it load the video file.

**Comment by adamfisher** [comment]
It sounds like you are not passing a proper local path. You might try some of the suggestions listed in this issue:

https://bitbucket.org/OctaneSoftware/octane.xam.videoplayer/issues/27/video-player-is-unable-to-find-an-embedded

**Comment by Graham-Bennett** [comment]
Thanks for the response but I am not trying to load an embedded resource but to load a file (selected by a user) from a local folder - I can't see any examples of this in the sample code. Is the best approach to get a stream from PCLStorage and pass it to VideoPlayer?

**Comment by Graham-Bennett** [comment]
**This works fine using PCLStorage:**
            _var localFolder = SpecialFolder.Current.Videos;
            var file = await localFolder.GetFileAsync("snow.mp4");
            var exists = await localFolder.CheckExistsAsync("snow.mp4");
            var filestream = await file.OpenAsync(FileAccess.Read);
            var videoSource = VideoSource.FromStream(()=>filestream, ".mp4");_

**Comment by Graham-Bennett** [comment]
Thanks for the advice.
