### ISSUE TITLE
set to always play in Landscape?

### ISSUE THREAD

**Issue by K232** [adamfisher/Xamarin.Forms.VideoPlayer#35]
Hi Adam,

is it possible to set the video to only play in landscape so that it does not support portrait mode? I also have the problems with stretching as described here https://bitbucket.org/OctaneSoftware/octane.xam.videoplayer/issues/2/android-fillmode-video-resolution-appears so I'd prefer to display all my videos in landscape only, regardless how the user holds the cell phone. Is that possible?

Many thanks!

**Comment by adamfisher** [comment]
The answer located here should help:

https://forums.xamarin.com/discussion/9454/how-to-force-app-in-landscape-mode

**Comment by K232** [comment]
Unfortunately not because it's about restricting the whole app, not just a single page.
But I understand that your video player is not able to restrict it so thanks for the info!
