### ISSUE TITLE
Fullscreen mode

### ISSUE THREAD

**Issue by fmeneuhe** [adamfisher/Xamarin.Forms.VideoPlayer#37]
Hi,
Is possible with VideoPlayer show a video in full window size without showing any status bar like youtube does?
Thanks

**Comment by adamfisher** [comment]
This component renders the native/default video player of each mobile platform and for some platforms, full screen support is either not straight forward or non-existent (a bit of an oversight in my opinion). 

In the interim, there are two options:

1. Create a new screen that only contains a VideoPlayer and set the `WidthRequest` and `HeightRequest` to match the parent container.
2. Create a custom renderer like the one shown below and use it to implement full screen capability yourself.

```
public class MyVideoPlayerRenderer : VideoPlayerRenderer
{
   protected override void OnElementPropertyChanged(object sender, PropertyChangedEventArgs e)
   {
       // Listen for a full screen property you added to an inherited version of the VideoPlayer and do something to make it full screen on each platform.
   }
}
```
