### ISSUE TITLE
Audio-only stream doesn't blank out last frame of previously playing video

### ISSUE THREAD

**Issue by Levent0z** [adamfisher/Xamarin.Forms.VideoPlayer#41]
If a video has only audio, then the last frame of the previously playing video remains. Expected: It should blank out.

**Comment by adamfisher** [comment]
That is the behavior of the native video player for whatever platform you happen to be on. One thing you might try is setting the source property to null before setting it to your audio source. If that doesn't work, you may have to create a [Xamarin custom renderer](https://developer.xamarin.com/guides/xamarin-forms/application-fundamentals/custom-renderer/) to customize the platform's native behavior of the `VideoPlayerRenderer` to suit your needs for this specific scenario.
