### ISSUE TITLE
How do I retry a failed a stream?

### ISSUE THREAD

**Issue by Levent0z** [adamfisher/Xamarin.Forms.VideoPlayer#42]
Setting VideoSource to null and back to the original value or a new string (of the original URL) doesn't seem to work. Neither does toggling AutoPlay.

**Comment by adamfisher** [comment]
You could hook into the `OnError` event and create a new `VideoPlayer` instance if it fails. Depending on the platform, the native player may have an internal state machine (like Android's `VideoView` which does not have a state that can be recovered from failure. In that case the resolution is to throw away that player instance and create a new one.
