### ISSUE TITLE
Video continues when screen locked on Android

### ISSUE THREAD

**Issue by bmanners** [adamfisher/Xamarin.Forms.VideoPlayer#43]
When a video is playing and you lock the screen the video continues to play. This consumes data & battery - not good.

**Comment by adamfisher** [comment]
Android's `VideoView` does not store instance state by default so you would need to add some code to your main activity to handle saving, pausing, and restoring the instance state of the player. That roughly looks something like this from this [Stack issue](https://stackoverflow.com/questions/11960730/resume-playing-videoview-from-onresume):

```
public void onResume() {
    super.onResume();
    myVideoPlayer.Seek(stopPosition);
    myVideoPlayer.Play();
}

// This gets called before onPause so pause video here.
public void onSaveInstanceState(Bundle outState) {
    super.onSaveInstanceState(outState);
    stopPosition = myVideoPlayer.CurrentTime; 
    myVideoPlayer.pause();
    outState.putInt("position", stopPosition);
}
```
Then in your `onCreate()` call the stopPosition from the bundle and set it globally:
```
protected void onCreate(Bundle args) {
    super.onCreate(args);
    if( args != null ) {
        stopPosition = args.getInt("position");
    }
}
```
