### ISSUE TITLE
Video state gets stuck at Preparing state for some streams.

### ISSUE THREAD

**Issue by Levent0z** [adamfisher/Xamarin.Forms.VideoPlayer#45]
I noticed that on iOS (both iPhone and iPad), for some streams, the video loads the first frame and gets stuck at "Preparing".  Once this happens, further normally working steams get stuck in Preparing also, even after starting to play normally.

I've hooked up The VideoPlayer's PlayerStateChange event handler to debug logs.
Here's some logs from the debug output. 

When a problematic link is activated:

Video State at 0 msecs = Initialized
VideoPlayer [INFO]: Video Source: http://tjktv.ercdn.net/tjktv_576p.m3u8

Video State at 30000 msecs = Prepared

At this point it never goes to playing mode. 
 
If I click a different video stream, that does work, the state doesn't stay in Playing mode, even though the video is definitely playing. Here's the debug output in that case:

Video State at 0 msecs = Initialized
VideoPlayer [INFO]: Video Source: http://abclive.abcnews.com/i/abc_live4@136330/index_1200_av-b.m3u8

Video State at 0 msecs = Prepared
Video State at 0 msecs = Playing
Video State at 0 msecs = Prepared

**Comment by adamfisher** [comment]
With AVPlayer, you have to add explicit exception domains to allow insecure HTTP video playback. So be sure to add entries for those domains.

**Comment by Levent0z** [comment]
What if the links are dynamic?

**Comment by Levent0z** [comment]
Also what about this: "https://techcrunch.com/2016/06/14/apple-will-require-https-connections-for-ios-apps-by-the-end-of-2016/"

**Comment by Levent0z** [comment]
I don't think insecure HTTP is the problem. I already had NSAllowsArbitraryLoads key in my info.plist. Both links I include in the issue description are HTTP, not HTTPS.

**Comment by Levent0z** [comment]
So just to reiterate the issue: the videoplayer shows the first frame and gets stuck. (http://tjktv.ercdn.net/tjktv_576p.m3u8). If I retry via a new instance of a VideoPlayer (like you suggested in a different post), I get the first frame at the time, and it gets stuck. I think that the underlying player is generating an error which VideoPlayer doesn't seem to be watching for.

**Comment by Levent0z** [comment]
Note: This issue appears to have gone away now that I'm always setting VideoSource to null before changing it to a non-null value.

**Comment by Levent0z** [comment]
One more note on this: I'm also calling pause method explicitly when I set VideoSource to null.
