### ISSUE TITLE
TapGestureRecognizer on VideoPlayer itself doesn't work on iOS.

### ISSUE THREAD

**Issue by Levent0z** [adamfisher/Xamarin.Forms.VideoPlayer#46]
When the video is playing, tapping on the video should do something, so I have a TapGestureRecognizer attached to the VideoPlayer itself, with data binding on Command. On Android, this works fine, on iOS, the command never hits.

Workaround: Add a ContentView the same size of VideoPlayer on the same grid, and attach it to that.

**Comment by adamfisher** [comment]
Unfortunately, your workaround appears to be the best approach. `GestureRecognizers` is a property that appears on every Xamarin Forms control that extends `View`. There is nothing extra a control utilizing gesture recognizers needs to do. It should "just work."

In the specific case of the video player, some platforms make use of a specific drawable surface area that does not respect the Xamarin Forms view hierarchy. So it makes sense gesture recognizers would behave differently in this aspect.
