### ISSUE TITLE
Does this library support Adaptive Bitrate Streaming (ABR)?

### ISSUE THREAD

**Issue by mortezasghari** [adamfisher/Xamarin.Forms.VideoPlayer#47]
I need this library but ABR capability is very important to me. could you verify if it has been supported?

sorry for my poor English!

**Comment by adamfisher** [comment]
ABR support will vary by platform and will be dictated by the platforms you wish to target. This component uses the [AVPlayer ](https://developer.apple.com/library/ios/documentation/AVFoundation/Reference/AVPlayer_Class) on iOS, the [MediaPlayer](http://developer.android.com/reference/android/media/MediaPlayer.html) on Android, and the [MediaElement](https://msdn.microsoft.com/en-us/library/windows/apps/system.windows.controls.mediaelement(v=vs.105).aspx) on Windows Phone. So you will want to take a look at the documentation for those specific components for each of the platforms you wish to target to know if it will suit your needs.
