### ISSUE TITLE
How can I set the YoutubeVideoId from code behind.

### ISSUE THREAD

**Issue by habeebmatrix** [adamfisher/Xamarin.Forms.VideoPlayer#48]
How can I set the YoutubeVideoId from code behind?

**Comment by adamfisher** [comment]
The `YouTubeVideoIdExtension` markup extension is not included with the nuget package. You need to grab it from the source code in this repository. Note that it is experimental and for real apps you will want to integrate with YouTube's official APIs.

An example is of `YouTubeVideoIdExtension` is [located here](https://github.com/adamfisher/Xamarin.Forms.VideoPlayer/blob/master/ChillPlayer/ChillPlayer/Pages/VideoPlayerQueuePage.xaml.cs#L64).

**Comment by habeebmatrix** [comment]
Thanks Adam. This is exactly what I was looking for. Its working fine.
