### ISSUE TITLE
Player won't render on Android

### ISSUE THREAD

**Issue by barryculhane** [adamfisher/Xamarin.Forms.VideoPlayer#49]
I used the trial version of this component to incorporate this video player into my Xamarin Forms app, with the sole purpose of playing web-based video files (http-accessible MP4 files).  I'm using FreshMvvm and I'm binding the video player **Source** property to a string property which has the video url.  It works fine in iOS, and so I went ahead and purchased a license.

I just now realized that it's not working on Android.  I'm testing on a Samsung Galaxy S4 running Android 5.0.1, but my colleagues have said it's also not working on newer Android 6.x phones.

As outlined in the documentation, I've added the **FormsVideoPlayer.Init(%licensekey%)** call to _MainActivity.OnCreate_ after the _Xamarin.Forms.Forms.Init(this, bundle)_ call, and I've added the INTERNET permission to the AndroidManifest file, but the video player is just showing up as a black panel.

The Visual Studio output log shows the following...

```
07-12 14:44:52.247 D/Mono    (23230): Assembly Ref addref Octane.Xam.VideoPlayer.Android[0xb39aca60] -> System[0xafb01a00]: 28
07-12 14:44:52.257 W/art     (23230): JNI RegisterNativeMethods: attempt to register 0 native methods for md5e55ab16df45b0a7c111e51d413f35949.VideoPlayerRenderer
07-12 14:44:52.457 I/mono-stdout(23230): VideoPlayer [INFO]: Video Source: https://qualialogstoragedev.blob.core.windows.net/usercontent/users/0000000/public/video.mp4
VideoPlayer [INFO]: Video Source: https://qualialogstoragedev.blob.core.windows.net/usercontent/users/0000000/public/video.mp4
07-12 14:44:52.807 I/Choreographer(23230): Skipped 78 frames!  The application may be doing too much work on its main thread.
07-12 14:44:53.098 V/MediaPlayer-JNI(23230): native_setup
07-12 14:44:53.098 V/MediaPlayer(23230): constructor
07-12 14:44:53.108 V/MediaPlayer(23230): setListener
07-12 14:44:53.108 E/ExtMediaPlayer-JNI(23230): QCMediaPlayer could not be located....
07-12 14:44:53.108 E/MediaPlayer-JNI(23230): QCMediaPlayer mediaplayer NOT present
07-12 14:44:53.118 V/MediaPlayer-JNI(23230): get_session_id()
07-12 14:44:53.128 D/MediaPlayer(23230): setDataSource IOException happend : 
07-12 14:44:53.128 D/MediaPlayer(23230): java.io.FileNotFoundException: No content provider: https://qualialogstoragedev.blob.core.windows.net/usercontent/users/0000000/public/video.mp4
07-12 14:44:53.128 D/MediaPlayer(23230): 	at android.content.ContentResolver.openTypedAssetFileDescriptor(ContentResolver.java:1074)
07-12 14:44:53.128 D/MediaPlayer(23230): 	at android.content.ContentResolver.openAssetFileDescriptor(ContentResolver.java:927)
07-12 14:44:53.128 D/MediaPlayer(23230): 	at android.content.ContentResolver.openAssetFileDescriptor(ContentResolver.java:854)
07-12 14:44:53.128 D/MediaPlayer(23230): 	at android.media.MediaPlayer.setDataSource(MediaPlayer.java:1087)
07-12 14:44:53.128 D/MediaPlayer(23230): 	at android.widget.VideoView.openVideo(VideoView.java:376)
07-12 14:44:53.128 D/MediaPlayer(23230): 	at android.widget.VideoView.access$2100(VideoView.java:73)
07-12 14:44:53.128 D/MediaPlayer(23230): 	at android.widget.VideoView$7.surfaceCreated(VideoView.java:657)
07-12 14:44:53.128 D/MediaPlayer(23230): 	at android.view.SurfaceView.updateWindow(SurfaceView.java:607)
07-12 14:44:53.128 D/MediaPlayer(23230): 	at android.view.SurfaceView$3.onPreDraw(SurfaceView.java:184)
07-12 14:44:53.128 D/MediaPlayer(23230): 	at android.view.ViewTreeObserver.dispatchOnPreDraw(ViewTreeObserver.java:921)
07-12 14:44:53.128 D/MediaPlayer(23230): 	at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:2164)
07-12 14:44:53.128 D/MediaPlayer(23230): 	at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1191)
07-12 14:44:53.128 D/MediaPlayer(23230): 	at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:6642)
07-12 14:44:53.128 D/MediaPlayer(23230): 	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:777)
07-12 14:44:53.128 D/MediaPlayer(23230): 	at android.view.Choreographer.doCallbacks(Choreographer.java:590)
07-12 14:44:53.128 D/MediaPlayer(23230): 	at android.view.Choreographer.doFrame(Choreographer.java:560)
07-12 14:44:53.128 D/MediaPlayer(23230): 	at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:763)
07-12 14:44:53.128 D/MediaPlayer(23230): 	at android.os.Handler.handleCallback(Handler.java:739)
07-12 14:44:53.128 D/MediaPlayer(23230): 	at android.os.Handler.dispatchMessage(Handler.java:95)
07-12 14:44:53.128 D/MediaPlayer(23230): 	at android.os.Looper.loop(Looper.java:145)
07-12 14:44:53.128 D/MediaPlayer(23230): 	at android.app.ActivityThread.main(ActivityThread.java:5942)
07-12 14:44:53.128 D/MediaPlayer(23230): 	at java.lang.reflect.Method.invoke(Native Method)
07-12 14:44:53.128 D/MediaPlayer(23230): 	at java.lang.reflect.Method.invoke(Method.java:372)
07-12 14:44:53.128 D/MediaPlayer(23230): 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1399)
07-12 14:44:53.128 D/MediaPlayer(23230): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1194)
07-12 14:44:53.138 D/MediaPlayer(23230): Couldn't open file on client side, trying server side
07-12 14:44:53.148 V/MediaPlayer(23230): setVideoSurfaceTexture
07-12 14:44:53.148 V/MediaPlayer-JNI(23230): setAudioStreamType: 3
07-12 14:44:53.148 V/MediaPlayer(23230): MediaPlayer::setAudioStreamType
07-12 14:44:53.148 V/MediaPlayer(23230): setVideoSurfaceTexture
07-12 14:44:53.148 V/MediaPlayer(23230): prepareAsync

```

The url for the 5-second MP4 file being used doesn't require authentication, and pasting it into any web browser allows the video to be played - I've tried it with HTTPS and HTTP and it doesn't work in either case.  Again, this works fine on iPhones running iOS 10.3.2, but won't work on Android devices.

Any suggestions?

**Comment by Nerololo** [comment]
Can you share some code or sample replo?

**Comment by barryculhane** [comment]
Sorry, I'm not really in a position to share the code due to the commercial nature of the app.

The Xamarin Components page for the plugin says _"A Video Player on Every Platform in 2 Minutes..."_ and it's a very straight-forward implementation - add the NuGet package, add the Xaml namespaces, add the Xaml control, set the properties, and that's all that's required.  The debug information in my post above shows that the plugin is getting the source property, and it works fine on iOS.  I'm looking for some pointers on why it wouldn't work on Android.  Is anything in the debug information above helpful?

Why would it be saying **QCMediaPlayer could not be located** ?
Why would it be throwing **_java.io.FileNotFoundException_ No content provider: https://...** ?

Are those expected debug messages on Android?

**Comment by barryculhane** [comment]
Never mind, got it working.  Just had to add **AutoPlay="true" DisplayControls="true"** and the video started up.  Without those, the player just displayed as a black panel and wasn't responding to touch/tap events.

The same error messages are still showing up in the debug log in Visual Studio 2015, but they don't appear to be indicative of a problem with the player, as it's now playing correctly.

**Comment by adamfisher** [comment]
I have not seen the `QCMediaPlayer` error before. QCMediaPlayer extends MediaPlayer from package android.media and provides extended APIs and interfaces to get and set MPD attributes for DASH protocol
in compatible Snapdragon builds. Perhaps Samsung devices have modified the SDK specifically around MediaPlayer? That is what this component uses under the hood but there is no use of `QCMediaPlayer` anywhere.

As for playing the video, if you were trying to set the URL and then manually invoke Play(), that would likely not work since the underlying player would not have loaded the media for streaming yet (race condition). If you want to be able to manually invoke Play(), you should hook into the `PlayerStateChanged` event and wait for the state to change to `Prepared`.

As for the mention of not finding a content provider, that is an Android feature and you may have to tweak the provider settings in your manifest to ensure URLs are handled properly for remote vs device file system path providers. A stock Android manifest like the chill player in this repo should provide an example.

Either way, glad to hear it is working for you.
