### ISSUE TITLE
Trying but some errors

### ISSUE THREAD

**Issue by tallmanBS** [adamfisher/Xamarin.Forms.VideoPlayer#5]
I followed the instructions; however, two errors in Visual studio 2016.
1. the FormsVideoPlayer.Init(""); is producing an error "CS0103: The name "FormsVideoPlayer" does not exist in the current context.  This is in my droid project which does have the component installed and showing.
2. The pcl receives following.  The assembly/dll isn't in the references.  How is it supposed to get their based on your instructions?

Severity	Code	Description	Project	File	Line	Suppression State
Error		Failed to resolve assembly: 'Octane.Xam.VideoPlayer, Culture=neutral, PublicKeyToken=null'	ChurchApp	C:\Users\Brent Safer\Documents\Visual Studio 2015\Projects\ChurchApp\ChurchApp\ChurchApp\ChurchApp.Pages.VideoViewPage.xaml		

I also have the question, will this player work with youtube livestreaming feature?

Thanks for your help.  I'd like this to work as I'm tired of fiddling with issues players.
Brent

**Comment by tallmanBS** [comment]
I downloaded the nuget Octane player into the Forms project and that seemed to resolve these issues.  If thats correct answer, then you might add to the install instructions as I don't seem to see it there.

Can you still answer the question regarding Livestreaming?  Will video viewer work with youtube livestreaming service?
Thanks.
Brent

**Comment by adamfisher** [comment]
Glad to hear nuget worked for you. The default way to install the component is through the Xamarin Component Store. I only uploaded it to nuget.org as an additional convenience but either way is fine. Unfortunately package management is never 100% fool-proof on everyone's machine (a.k.a package hell).

As for streaming, folks have had mixed success. Keep in mind it depends on the platform as to what codecs/formats are supported. I am not familiar with YouTube's Live Streaming but if they give you a URL, the easiest thing to do would be to plug it in and give it a go on the platforms you are targeting to see if it works for you.
