### ISSUE TITLE
Video control in Android is no resizing

### ISSUE THREAD

**Issue by ghost** [adamfisher/Xamarin.Forms.VideoPlayer#50]
Hi i bought your control and work fine in iOS, is resizing the control respecting the aspect of the video. But in Android is not.

I see this thread, but i cant fix it :(
https://bitbucket.org/OctaneSoftware/octane.xam.videoplayer/issues/2/android-fillmode-video-resolution-appears

Here is the code i use, i tried put in a StackLayout, ContentView, direct in the content page, also i tried combination of FillMode, but cant fix it :(

```
 <AbsoluteLayout>
        <o:VideoPlayer AutoPlay="True" AbsoluteLayout.LayoutBounds="0, 0, 1.0, 1.0" AbsoluteLayout.LayoutFlags="All"
                           Source="{Binding Publicacion.UrlArchivo}" FillMode="ResizeAspect" >
        </o:VideoPlayer>
    </AbsoluteLayout>
```

Can you help me with some solutions or workaround, pleeeeaaseeeeee? :(

![ios prueba](https://user-images.githubusercontent.com/16414178/28240179-ea83689a-6941-11e7-8ff7-45427ec7846c.jpg)
![android prueba](https://user-images.githubusercontent.com/16414178/28240180-ecd4637e-6941-11e7-9629-a7739d7952ba.png)

**Comment by adamfisher** [comment]
Please see issue #3
