### ISSUE TITLE
Forms - iOS Crashes while in cells

### ISSUE THREAD

**Issue by alanspires** [adamfisher/Xamarin.Forms.VideoPlayer#52]
Listview with cells containing the plater.

exception: An instance 0x610000403480 of class AVPlayer was deallocated while key value observers were still registered with it.

Happens while scrolling or navigating.

**Comment by adamfisher** [comment]
Having multiple instances of the player on a single page is not supported. When Xamarin Forms loads the ListView, it would initialize every video player on the page which for Android can cause performance issues and potentially crash the app. Video is a heavy thing and people probably won't like their bandwidth being depleted by a page running many videos. Even if you don't set `AutoPlay="True"`, as soon as you specify a URL for the player, it will begin asynchronously opening it in the background and preparing the stream for playback.

A workaround to your desired scenario would be to include only one instance of the player on the screen and as user's scroll through your list of video's you swap out the thumbnail in the cell with the player instance, entering the corresponding URL.
