### ISSUE TITLE
Can't choose the video transport type

### ISSUE THREAD

**Issue by ghost** [adamfisher/Xamarin.Forms.VideoPlayer#54]
It seems we can't choose the transport type for the video on the client side.
(UDP, TCP, RTP over RTSP and RTP over RTSP over HTTP(S)).

**Comment by adamfisher** [comment]
The goal of this component is to render the native video player of each platform. So on Android we use the `VideoView` and iOS uses the `AVPlayer`. So it really comes down to what each individual platform supports and choosing the appropriate intersection of compatible streaming protocols, or providing a different URL for each platform using Xamarin Forms `<OnPlatform>` functionality.

If you want to get more fine-grained control of the component, you can extend the `VideoPlayerRenderer` in your iOS or Android project and access the `Control` property in your own custom renderer to access native methods and fields of the underlying video player.
