### ISSUE TITLE
FillMode not working on Android.

### ISSUE THREAD

**Issue by leoalvaleo** [adamfisher/Xamarin.Forms.VideoPlayer#58]
FillMode is not working on Android devices and no matter which option I choose the aspect ratio is still stretched.

There is a solution in issue #3 but I am not allowed to see the content of the page (Access Denied).

Thanks!

**Comment by leoalvaleo** [comment]
I ended up finding a partial solution to my problem. It may not work for everyone, but in my situation, I knew what resolution the video has before even running it (1920x1080). With that, I created an AbsoluteLayout and I set the Bounds of the video according to the size of the screen.

First of all I collected information from the screen, such as its width and height. The width of the video should always be the width of the screen and in the case of my video resolution, its height should always be 56% of the total size of its width.

**Comment by adamfisher** [comment]
Updated issue #3 with code from BitBucket repo.
