### ISSUE TITLE
Video not pausing on home button

### ISSUE THREAD

**Issue by cdamose** [adamfisher/Xamarin.Forms.VideoPlayer#6]
Last week we bought licensed package : "com.tranzaura.all"

While video playing suddenly i pressed home button of mobile. video player is not pausing the video. When i resume the application it shows the completed state of video.

**Comment by adamfisher** [comment]
What platform? Does the video complete because it ended before you came back?

**Comment by cdamose** [comment]
We using android platform, video doesn't pause when we press home button,
Thanks
Amose

**Comment by EkambaramE** [comment]
Try to pop up the current view or remove the page in the current stack, then you can able to pause the video. Another option in the onDisappearing method you can do pause and Hide the player

**Comment by cdamose** [comment]
EkambaramE it's not working

**Comment by EkambaramE** [comment]
Can you share the code ..??

**Comment by cdamose** [comment]
Are you using chill player, just play video using chill player, press home
button in device while video is running video is ended background,
ondisappear also not calling while press home button

Thanks
Amose

**Comment by adamfisher** [comment]
It does not appear to be native behavior so I would recommend creating a Xamarin Forms custom renderer but even then, messing with the home button might be limited:

http://stackoverflow.com/questions/4783960/call-method-when-home-button-pressed-on-android

In your custom renderer you could create something like this potentially to pause it:

```csharp
public override bool OnKeyDown([GeneratedEnum] Keycode keyCode, KeyEvent e)
{
	if(keycode == Keycode.Home)
	{
		Player.Stop();
	}
	return base.OnKeyDown(keyCode, e);
}
```

**Comment by adamfisher** [comment]
Another approach might be to keep a reference of your video player and you can add logic to the lifecycle methods that Xamarin Forms calls when your app goes to the background as shown below. I am hesitant to make the player "smart" in handling this as it is not default/native behavior which Xamarin Forms controls strive to achieve.

```csharp
public class App : Application  
{
    protected override void OnSleep ()
    {
        myVideoPlayer.Pause();
    }

    protected override void OnResume ()
    {
        myVideoPlayer.Play();
    }
}
```

**Comment by cdamose** [comment]
I tried this way but still video is running background it not pausing...

**Comment by adamfisher** [comment]
If that doesn't work out, You will need to bubble up the event of the native `OnPause()` method from the `MainActivity` of your Android project, pausing the video when that fires. 

https://developer.xamarin.com/api/member/Android.App.Activity.OnPause

**Comment by cdamose** [comment]
I tried this method, but it still doesn't achieve the video is running background and it is not pausing
