### ISSUE TITLE
Custom http headers in player

### ISSUE THREAD

**Issue by PaulVrugt** [adamfisher/Xamarin.Forms.VideoPlayer#61]
Hello,

I'm looking into being able to use this component. In our situation, the video to be played comes from a API. This api requires custom http headers to authenticate the user. However, this component doesn't offer the possibility to pass custom http headers to the component.

An alternative is directly passing the stream of my own request to the api to the component. However, this causes exceptions since the component tries to seek in the stream, which is not possible in a responsestream, without buffering the ENTIRE video in the stream before passing it to the component.

Is it possible to add the custom http header support?

**Comment by adamfisher** [comment]
This is not something exposed by default but you could create a **[Xamarin Forms custom renderer](https://developer.xamarin.com/guides/xamarin-forms/application-fundamentals/custom-renderer/)** for the platforms you wish to modify the behavior of how the source gets set with a header. Below is a rough idea of how you could accomplish it for Android.

```
public class MyVideoPlayerRenderer : VideoPlayerRenderer
    {
        protected override async void OnElementPropertyChanged(object sender, PropertyChangedEventArgs e)
        {
            if (e.PropertyName == VideoPlayer.SourceProperty.PropertyName)
            {
                var newSource = Element.Source;
                var videoSourceHandler = VideoSourceHandler.Create(newSource);
                var path = await videoSourceHandler.LoadVideoAsync(newSource, new CancellationToken());
                Control.SetVideoURI(global::Android.Net.Uri.Parse(path), new Dictionary<string, string>(){{ "X-Header-Key", "HeaderValue" }});
            }
            else
            {
                base.OnElementPropertyChanged(sender, e);
            }
        }
    }
```

Note that you would want to still call the base implementation for all other properties. The drawback to overriding the setting of the source is that you end up losing some small behavior (e.g. IsLoadingProperty and Intitialized event) but you can either fire these manually when you override it or just ignore them if you don't plan to use them.

**Comment by NPC-CPT** [comment]
I'm trying to implement this on iOS, could you elaborate on:

e.PropertyName == VideoPlayer.SourceProperty.PropertyName, this conditional never evaluates to true on iOS

Control._, I'm not sure what a UIView expects from me.

Thanks in advance
