### ISSUE TITLE
Player Uses Streams Like a File

### ISSUE THREAD

**Issue by NPC-CPT** [adamfisher/Xamarin.Forms.VideoPlayer#62]
I'm making a custom stream. I don't want the player to read the entire stream at once and only buffer as it goes, and I need to define how it reads from the array. When passed a stream, the player reads all the content from the stream before attempting to play the file. Making my custom stream useless for this purpose. Is it possible to currently define how the player is reading the file?

**Comment by adamfisher** [comment]
See the code in issue #61. This provides an example of how to create a Xamarin Forms custom renderer to access the source property in your native project which allows you to control how the source is loaded. You would do this once for each platform you are targeting. You then have control over how the URI denoted by `newSource` gets loaded.

**Comment by toverux** [comment]
@NPC-CPT Hello, have you managed to do that? I'll have to implement the same thing and all of that wasn't planned :) Any help would be appreciated.
