### ISSUE TITLE
Octane.Xam.VideoPlayer.Licensing.VideoPlayerLicenseException occurred

### ISSUE THREAD

**Issue by toyins46** [adamfisher/Xamarin.Forms.VideoPlayer#64]
I tried using the License Key that I have just purchased, specifically for the Project that I bought it for. However, I'm getting this error message.

Octane.Xam.VideoPlayer.Licensing.VideoPlayerLicenseException occurred
  HResult=0x80131500
  Message=The specified license key is invalid or incompatible with this mobile application.
You are attempting to use functionality that is not included in the trial version of this component. Please consider purchasing a licensed copy at https://components.xamarin.com/view/video-player.
  Source=<Cannot evaluate the exception source>
  StackTrace:
   at Octane.Xam.VideoPlayer.Licensing.VideoPlayerLicense.Initialize(String licenseKey)
   at Octane.Xam.VideoPlayer.UWP.FormsVideoPlayer.Init(String licenseKey)
   at ClaimAll.UWP.App.OnLaunched(LaunchActivatedEventArgs e) in C:\Develop_Practice\Mobile\Xamarin\ClaimAllDev\ClaimAll\ClaimAll\ClaimAll.UWP\App.xaml.cs:line 64

Please let me know how this can be resolved.

Thanks.

**Comment by adamfisher** [comment]
This is unfortunately typical for some new users. The build process caches some things so it may be necessary to clear some things up. Here are some things to try:

1. Try resetting the simulator completely and uninstalling the mono shared runtime as well as your application on the android emulator. This will ensure a fresh environment.
2. Try using a different URL to see if there is something going on with your networking environment (if you happen to be behind a corporate firewall). I also posted a video tutorial on how to setup a fresh project and play a video on the simulator in a just a couple of minutes: https://youtu.be/JJ8NuGe_Fr8?t=11m26s
3. Try running on a different machine.

**Comment by toyins46** [comment]
Hi Adam,
I tried running my ClaimAll app on a different PC using a different flavor of Visual Studio 2017. However, I’m getting an error message
“Unhandled Exception:

Octane.Xamarin.Forms.VideoPlayer.Licensing.VideoPlayerLicenseException: The specified license key is invalid or incompatible with this mobile application.
You are attempting to use functionality that is not included in the trial version of this component. Please consider purchasing a licensed copy at https://components.xamarin.com/view/video-player. occurred”.

I have a valid License Key, what could be the problem? I have cleaned up the solution and rebuilt it but the problem still persists.

Please let me know how I can resolve this issue.

Thanks,

Toyin.
