### ISSUE TITLE
Audio when in "silent" mode

### ISSUE THREAD

**Issue by nrweber** [adamfisher/Xamarin.Forms.VideoPlayer#67]
Is there any way to get the audio to still play on a video even if the iPhone's ringer switch is in "silent" mode? It may seem strange to want to ignore this but for an app that plays videos (like the YouTube app), the user is expecting there to be audio with the video.

**Comment by adamfisher** [comment]
The player exposes a `Volume` property but if you need more control, you can access Android's `AudioManager` providing access to different audio sources in your native Android project.

https://developer.android.com/reference/android/media/AudioManager.html
