### ISSUE TITLE
Video playback doesn't start until video buffering state reaches 90% 

### ISSUE THREAD

**Issue by SudharsanKrishnamoorthy** [adamfisher/Xamarin.Forms.VideoPlayer#68]
Hi Adam,
         We are facing some issue in octane player while loading the videos in iOS devices through mobile data, when we try to stream a video through URL , playback doesn't start until the buffering state reaches 90%. 
We also tried testing the above case in android devices , its working as expected. 
Can you please help us with this issue.?

Thanks.

**Comment by adamfisher** [comment]
The iOS implementation is using the default native `AVPlayerViewController` so it is largely controlled by Apple. However if you create a [Xamarin Forms custom renderer](https://developer.xamarin.com/guides/xamarin-forms/application-fundamentals/custom-renderer/) and extend the `VideoPlayerRenderer` in your iOS project, you should be able to get access to the player via the `Control` property which would allow you to set [automaticallyWaitsToMinimizeStalling](https://developer.apple.com/documentation/avfoundation/avplayer/1643482-automaticallywaitstominimizestal).

**Comment by eopeter** [comment]
How do I access the player in the Renderer. Tried following and didn't work: I also tried AVPlayerView which is what the Control is but seems its a MacOS only view based on Apple Docs.

`protected override void OnElementChanged(ElementChangedEventArgs<VideoPlayer> e)
        {
            base.OnElementChanged(e);
            if(Control != null)
            {
                var layer =  (AVPlayerLayer)Control.Layer;
                layer.Player.AutomaticallyWaitsToMinimizeStalling = true;
            }
        }`
