### ISSUE TITLE
Question - Octane.Xam.VideoPlayer.Licensing.VideoPlayerLicenseException: You cannot play a video longer than 15 seconds.

### ISSUE THREAD

**Issue by sramil** [adamfisher/Xamarin.Forms.VideoPlayer#69]
I purchased the license key and called the Init method in the AppDelegate class, will this error  disappear when I deploy my app to iOS? Is there a way to remove this while I'm still in development?

Octane.Xam.VideoPlayer.Licensing.VideoPlayerLicenseException: You cannot play a video longer than 15 seconds.

You are attempting to use functionality that is not included in the trial version of this component. Please consider purchasing a licensed copy at https://components.xamarin.com/view/video-player.

**Comment by adamfisher** [comment]
The message will go away once you insert the license key into the init() method call. Calling it without any parameters makes the player work in trial mode which is why you see that message. More information can be found on the [Xamarin Component Store page](https://components.xamarin.com/view/video-player).

**Comment by sramil** [comment]
Sorry Adam, I wasn't clear, I added the license key in the Init call, but I was running it on the simulator. Does it need to be run on a test device? Thanks!

**Comment by sramil** [comment]
I just used a test device for my app and I'm still getting the exception after playing the video for 15 seconds. I have the license key added in the Init call. This is my code:

videoPlayer.Source = YouTubeVideoIdExtension.Convert(videoId);
videoPlayer.Play();

XAML looks like this:

<o:VideoPlayer 
        x:Name="videoPlayer" 
        AutoPlay="True"
        PlayerStateChanged="VideoPlayer_OnPlayerStateChanged" 
      />

**Comment by sramil** [comment]
Update: It is working now.

I moved the Init call just right after Xamarin.Forms.Forms.Init() as instructed. Previously, it was added after Xamarin.Forms.Forms.Init(), but there are other codes written between these 2 calls. Moving it and making sure it is called right after Xamarin.Forms.Forms.Init() fixes my problem.
