### ISSUE TITLE
Need to intercept Exit FullScreen event!

### ISSUE THREAD

**Issue by Endriu87** [adamfisher/Xamarin.Forms.VideoPlayer#71]
Hi.
  My application is used and set up in portrait mode. 
I need to intercept the right moment when the user exit from fullscreen video (in landscape mode) to reset orientation to portrait.
I already have a dependency service that works like a charm to force orientation as i desire; the problem is to intercept the event (the playerstatechanged won't be raised in this case).
Without this feature the plugin will be unuseful for me :(.
Please let me know asap if there's already a way to achieve this.

Thanks.

**Comment by adamfisher** [comment]
The player does not expose a full screen property because not all platforms support it by default. You will want to create a xamarin forms custom renderer and extend the video player renderer in your native platform project. This will give you access to the native video player of each platform where you should be able to hook into the native event system to detect that you've exited full screen. At that point it's really a matter of looking at the documentation for each platforms implemented which would be the avplayer for iOS and the media player for Android.

**Comment by Endriu87** [comment]
Thanks for you response.  I create a customrenderer but now i need to take access to the native videoplayer control...Is is AVPlayer for IOS? could you suggest me how to get the control??

   public VideoPlayerCustomRenderer()
      {
            
            ((AVPlayer)this.Control). ????


        }
I need the control to check which method is raised after the exit fullscreen event..

Thanks in advance.

**Comment by Endriu87** [comment]
Hi Adam...I bought a new fresh license of your plugin (needed for change native behaviour).. but i need you support and help as far as you can. I create my own custom render and i add observer to bounds in        

<code>


		public override void MovedToWindow()
        {
            base.MovedToWindow();
            PlayerControl.ContentOverlayView.AddObserver(this, new NSString("bounds"), NSKeyValueObservingOptions.New | NSKeyValueObservingOptions.Old, IntPtr.Zero);

		}		
</code>

<code>


       

          public override void ObserveValue(NSString keyPath, NSObject ofObject, NSDictionary change, IntPtr context){
            base.ObserveValue(keyPath, ofObject, change, context);
            if (ofObject == PlayerControl.ContentOverlayView)
            {
                if (keyPath == "bounds")
                {
                    var oldRect = change.ValueForKey(new NSString("NSKeyValueChangeOldKey")) as NSValue;
                    var newRect = change.ValueForKey(new NSString("NSKeyValueChangeNewKey")) as NSValue;
                    var oldBounds = oldRect.CGRectValue;
                    var newBounds = newRect.CGRectValue;

                    var wasFullscreen = oldBounds == UIScreen.MainScreen.Bounds;
                    var isFullscreen = newBounds == UIScreen.MainScreen.Bounds;

                    if (isFullscreen && !wasFullscreen)
                    {
                        Console.WriteLine(oldBounds == new CGRect(0, 0, newBounds.Size.Height, newBounds.Size.Width)
                            ? "rotated fullscreen"
                            : "entered fullscreen");
                    }
                    else if (!isFullscreen && wasFullscreen)
                    {
                        DependencyService.Get<IOrientationManager>().ForcePortrait();
                        Debug.WriteLine(@"exited fullscreen");
                    }
                }
            }
        }


The problem is that when i enter/exit full screen the applciation never stop in debug in observevalue even the bounds were change...Am i missing something? Am i Wrong?

In the case of play/pause the application enter in observevalue with the correct keypath (rate in this case).

What can you suggest to fix??

I read this wanring in console Warning: <AVPlayerViewController: 0x7f8b669b1200> is trying to exit/enter full screen, but is not in its view's window's view controller hierarchy. This results in undefined behavior.
Maybe they could be the reason of this issue?

Thanksing you in advance.

please let me know.
