### ISSUE TITLE
Need to observe enter/exit fullscreen AVPlayerViewController  custom renderer

### ISSUE THREAD

**Issue by Endriu87** [adamfisher/Xamarin.Forms.VideoPlayer#73]
Hi Adam...I bought a new fresh license of your plugin (needed for change native behaviour).. but i need you support and help as far as you can. I create my own custom render and i add observer to bounds in

 	public override void MovedToWindow()
    {
        base.MovedToWindow();
        PlayerControl.ContentOverlayView.AddObserver(this, new NSString("bounds"), NSKeyValueObservingOptions.New | NSKeyValueObservingOptions.Old, IntPtr.Zero);

	}		
       public override void ObserveValue(NSString keyPath, NSObject ofObject, NSDictionary change, IntPtr context){
        base.ObserveValue(keyPath, ofObject, change, context);
        if (ofObject == PlayerControl.ContentOverlayView)
        {
            if (keyPath == "bounds")
            {
                var oldRect = change.ValueForKey(new NSString("NSKeyValueChangeOldKey")) as NSValue;
                var newRect = change.ValueForKey(new NSString("NSKeyValueChangeNewKey")) as NSValue;
                var oldBounds = oldRect.CGRectValue;
                var newBounds = newRect.CGRectValue;

                var wasFullscreen = oldBounds == UIScreen.MainScreen.Bounds;
                var isFullscreen = newBounds == UIScreen.MainScreen.Bounds;

                if (isFullscreen && !wasFullscreen)
                {
                    Console.WriteLine(oldBounds == new CGRect(0, 0, newBounds.Size.Height, newBounds.Size.Width)
                        ? "rotated fullscreen"
                        : "entered fullscreen");
                }
                else if (!isFullscreen && wasFullscreen)
                {
                    DependencyService.Get<IOrientationManager>().ForcePortrait();
                    Debug.WriteLine(@"exited fullscreen");
                }
            }
        }
    }
The problem is that when i enter/exit full screen the applciation never stop in debug in observevalue even the bounds were change...Am i missing something? Am i Wrong?

In the case of play/pause the application enter in observevalue with the correct keypath (rate in this case).

What can you suggest to fix??

I read this wanring in console Warning: <AVPlayerViewController: 0x7f8b669b1200> is trying to exit/enter full screen, but is not in its view's window's view controller hierarchy. This results in undefined behavior. Maybe they could be the reason of this issue?

Thanking you in advance.

please let me know.

I tried also observing videobound property of the playerself but the i faced the same issue.

**Comment by adamfisher** [comment]
When adding the observer, I call it something like this:

```
PlayerControl.ContentOverlayView.AddObserver(this, (NSString)"bounds", 0, Handle);
```

**Comment by Endriu87** [comment]
I just tried and it doesn't work....when i expand to full screen or exit..the application never stop in debug...I add the observer in movedtowindows ovverride...maybe it is the wrong point?...can you try an example for me??

thank you in advance.. i'm getting crazy :(
Andrea

**Comment by nrvraghu** [comment]
Try the following code it may help full.
The following is working for me in WKWebView in swift 4.1 The main part of the WKWebView in WKwebviewConfiguration
// Code
wkwebView.navigationDelegate = self
wkwebView.allowsBackForwardNavigationGestures = true
self.wkwebView =  WKWebView(frame: CGRect(x: 0, y: 0, width: self.view.frame.size.width, height: self.view.frame.size.height))
let config = WKWebViewConfiguration()
config.allowsInlineMediaPlayback = true
wkwebView = WKWebView(frame: wkwebView.frame, configuration: config)
self.view.addSubview(wkwebView)
self.wkwebView.load(NSURLRequest(url: URL(string: self.getUrl())!) as URLRequest)
