### ISSUE TITLE
Question, iOS vs Andriod

### ISSUE THREAD

**Issue by JMNewsome** [adamfisher/Xamarin.Forms.VideoPlayer#76]
I am interested in this plugin and one of the features that I am looking to do that I have already set on iOS is a video preview. With iOS I can just call the video component and set a source without autoplay and it will give me a visual of the first frame which can be used as a thumbnail, the same exact code just leads to a black box on Andriod. How can I produce the same effect on andriod so a loaded video does not just show a black box but at least the first frame of the video to be played?

**Comment by adamfisher** [comment]
Something like the following code might be a good starting point. It sets the player to fire the `TimeElapsedInterval` every second. Upon the first time the `TimeElapsed` event fires, you can disable it from firing further by setting `TimeElapsedInterval = 0` and pausing the player while doing so. This relies on the fact the video is set to auto play so you should place this code in your page's constructor. Depending on how soon you pass a video path into the `Source` property, you may need to also set the source inside your code-behind as well or set `AutoPlay="false"` in the XAML so it doesn't begin playback prematurely before the time elapsed event is setup if you truly want the first frame.

```
videoPlayer.TimeElapsedInterval = 1;
videoPlayer.TimeElapsed += (sender, args) =>
{
   videoPlayer.TimeElapsedInterval = 0;
   videoPlayer.Pause();
};
```
