### ISSUE TITLE
Play 1GB encrypted video file

### ISSUE THREAD

**Issue by anishmm** [adamfisher/Xamarin.Forms.VideoPlayer#79]
We have some video files that's is more than 1 GB and it's in encrypted format. Is there is any options to play this file ?  Decrypt to normal format is taking too much time and people can copy the original files. Is there is any local file streaming option is available ?

**Comment by adamfisher** [comment]
It is just the native platform video player so if the platform(s) you are targeting don't support it by default then neither will the component. If you are manipulating the file in memory, you could pass it using something like this code snippet assuming you have decrypted the stream:

`myVideoPlayer.Source = VideoSource.FromStream(() => ...);`
