### ISSUE TITLE
No video is displaying

### ISSUE THREAD

**Issue by Nicolas40a** [adamfisher/Xamarin.Forms.VideoPlayer#8]
Hi,

I am trying this framework and really would like to use it eventually but so far it doesn't work on my project.
Before trying to add it up to my actual app, I tried on a blank page and first I just tried to display your ocean sample video in XAML and in C# but nothing appears on the screen. If I add labels before and after, I can see that room is made for the video but nothing is playing, and I don't have the display controllers neither even with the parameter DisplayControls = true.
I didn't forget to add the INTERNET authorization on Android because this is where I am testing it on right now.

Is there a way to display some logs or to get information on what is it going on and why it is not working?

Thank you

Nicolas Q

**Comment by Nicolas40a** [comment]
I would definitely buy the full version if I could get the trial version to work.

**Comment by Nicolas40a** [comment]
Solved by myself.

The problem was that I didn't have the init method in my android project, thinking that because I was using the trial version I didn't need to have it.
The way it is explained on the getting started, it looks like it is only required to validate the license key so you may think you don't need it if you want the trial version. Also, I didn't find where it is written that for the trial version you have to write the init method with no license key given.

**Comment by adamfisher** [comment]
The [Getting Started Guide](https://github.com/adamfisher/Xamarin.Forms.VideoPlayer/blob/master/GettingStarted.md) is written assuming you have already purchased it. The Chill Player example application that comes packaged with the component shows the component setup in demo mode. I suppose that could be made more explicit for the future 👍 

Fixed: https://github.com/adamfisher/Xamarin.Forms.VideoPlayer/commit/22c387109ddf4ef6e5da9c8ce3e0fdbe00cca84d
