### ISSUE TITLE
Does VideoPlayer support NetStandard?

### ISSUE THREAD

**Issue by satputerohan** [adamfisher/Xamarin.Forms.VideoPlayer#80]
Hi Adam, 
I am using Video Player since a few months. Now I want to update my project to .NetStandard as Microsoft is deprecating the PCL. Does VideoPlayer support NetStandard?

**Comment by adamfisher** [comment]
This is address in Release 2.0.0

https://github.com/adamfisher/Xamarin.Forms.VideoPlayer/releases/tag/2.0.0
