### ISSUE TITLE
Failed to resolve assembly

### ISSUE THREAD

**Issue by jlmacedo** [adamfisher/Xamarin.Forms.VideoPlayer#81]
Hi,

I tried to test your plugin, but I receive the error: Failed to resolve assembly: 'Octane.Xam.VideoPlayer, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null'

Plugin Version: 2.0.0

**Comment by adamfisher** [comment]
The namespace changed in 2.0 to `Octane.Xamarin.Forms.VideoPlayer` and is a breaking change. I would uninstall and reinstall via nuget to remove the old reference under the References node of your project.

**Comment by jlmacedo** [comment]
That's working, thank you!

**Comment by jlmacedo** [comment]
I've a doubt, your video player have seekToTime function ?
