### ISSUE TITLE
SeekToTime ?

### ISSUE THREAD

**Issue by jlmacedo** [adamfisher/Xamarin.Forms.VideoPlayer#82]
I've a doubt, your video player have seekToTime function ?

**Comment by adamfisher** [comment]
There is not currently an operation to seek to a specific time but there is a `SeekCommand` and corresponding `Seek` method that will increment/decrement a specific number of seconds in relation to where you are in the playback. You can find out more about this in [the documentation](https://github.com/adamfisher/Xamarin.Forms.VideoPlayer/blob/master/GettingStarted.md#commands).

This would be a good enhancement. I will mark this issue as such for future consideration.

In the interim, you can achieve SeekTo by effectively examining the `CurrentTime` property and add/substract seconds from that value and pass it to the seek operation to move to a specific time in the playback timeline.

**Comment by jlmacedo** [comment]
Ok, thank you!
