### ISSUE TITLE
Unhandled Exception:  System.NullReferenceException: Object reference not set to an instance of an object.

### ISSUE THREAD

**Issue by JMNewsome** [adamfisher/Xamarin.Forms.VideoPlayer#83]
VideoPlayer -> Non-public members -> NativeRenderer -> Control = null

I am getting a null reference exception when calling pause() on a VideoPlayer element that is inside of a CarouselView element. What I believe is happening that CarouselView keeps elements Current-1,Current,Current+1 active and disposes of the elements until they are within range, I believe this is causing VideoPlayer to dispose of the view but the object itself is still reference, when calling Pause() through code I have mocked to be OnAppearing/OnDisappearing through ContentView forces me to have a NullReferenceException error

I believe this can either be remedied by either making sure within the Pause(),Stop(),Play() commands to make sure that the control is not null at calling time, or provide a way to check if the Videoplayer has been disposed, all other variables within VideoPlayer appear to be set but the player itself is returning null when it is not active.

01-08 13:52:47.757 I/MonoDroid(14064): System.NullReferenceException: Object reference not set to an instance of an object.
01-08 13:52:47.757 I/MonoDroid(14064):   at Octane.Xamarin.Forms.VideoPlayer.Android.Renderers.VideoPlayerRenderer.CanPause () [0x00006] in <67d7e1a4bd474f999f9b7a265e27ab48>:0 
01-08 13:52:47.757 I/MonoDroid(14064):   at Octane.Xamarin.Forms.VideoPlayer.Android.Renderers.VideoPlayerRenderer.Pause () [0x00000] in <67d7e1a4bd474f999f9b7a265e27ab48>:0 
01-08 13:52:47.757 I/MonoDroid(14064):   at Octane.Xamarin.Forms.VideoPlayer.VideoPlayer.<.ctor>b__77_2 () [0x0000a] in <92da1586271f491697094c2e7205b6a2>:0 
01-08 13:52:47.757 I/MonoDroid(14064):   at Xamarin.Forms.Command+<>c__DisplayClass5_0.<.ctor>b__0 (System.Object o) [0x00000] in D:\agent\_work\1\s\Xamarin.Forms.Core\Command.cs:87 
01-08 13:52:47.757 I/MonoDroid(14064):   at Xamarin.Forms.Command.Execute (System.Object parameter) [0x00000] in D:\agent\_work\1\s\Xamarin.Forms.Core\Command.cs:107 
01-08 13:52:47.757 I/MonoDroid(14064):   at Octane.Xamarin.Forms.VideoPlayer.VideoPlayer.Pause () [0x00006] in <92da1586271f491697094c2e7205b6a2>:0 
01-08 13:52:47.757 I/MonoDroid(14064):   at Muovs.Testing.CarouselViewEXT.DisplayPage.OnDisappearing () [0x00037] in C:\Users\Jozef\Desktop\Development\Applications\Muovs\Project\Muovs\Muovs\Muovs\Testing\CarouselViewEXT\DisplayPage.xaml.cs:38 
01-08 13:52:47.757 I/MonoDroid(14064):   at Muovs.Testing.CarouselView.<.ctor>b__1_0 (System.Object s, CarouselView.FormsPlugin.Abstractions.PositionSelectedEventArgs e) [0x0007a] in C:\Users\Jozef\Desktop\Development\Applications\Muovs\Project\Muovs\Muovs\Muovs\Testing\CarouselView.xaml.cs:75 
01-08 13:52:47.757 I/MonoDroid(14064):   at CarouselView.FormsPlugin.Abstractions.CarouselViewControl.SendPositionSelected () [0x0001d] in <82d2a2414b2245f8ae8f9cbb927e1d5e>:0 
01-08 13:52:47.757 I/MonoDroid(14064):   at CarouselView.FormsPlugin.Android.CarouselViewRenderer.ViewPager_PageScrollStateChanged (System.Object sender, Android.Support.V4.View.ViewPager+PageScrollStateChangedEventArgs e) [0x0003f] in <98afd48205e1402cbb4986578e5c0d9e>:0 
01-08 13:52:47.757 I/MonoDroid(14064):   at Android.Support.V4.View.ViewPager+IOnPageChangeListenerImplementor.OnPageScrollStateChanged (System.Int32 state) [0x00017] in <fc4222de5c684a9abf7cc4821baac4cd>:0 
01-08 13:52:47.757 I/MonoDroid(14064):   at Android.Support.V4.View.ViewPager+IOnPageChangeListenerInvoker.n_OnPageScrollStateChanged_I (System.IntPtr jnienv, System.IntPtr native__this, System.Int32 state) [0x00008] in <fc4222de5c684a9abf7cc4821baac4cd>:0 
01-08 13:52:47.757 I/MonoDroid(14064):   at (wrapper dynamic-method) System.Object:7212d9cd-7859-43bc-90c6-b8a476ce237b (intptr,intptr,int)

**Comment by adamfisher** [comment]
There does appear to be a tweak that can be made. This will be scheduled for the next release.

In the interim, you should be able to swap the player to the next carousel position, keeping only a single instance. It is important to only have one player per page since Android's `SurfaceView` doesn't respect the Xamarin Forms view hierarchy nicely. 

Another option might be to pause before the user slides the carousel - perhaps with a gesture recognizer that recognizes the tap before the slide? I haven't played around with the carousel enough to know.

**Comment by JMNewsome** [comment]
I am also seeing issue with the iOS where if I call a resize on a parent container that the video exists in, it causes the VideoPlayer to refresh but essentially the object before resizing occurs still exists as well as the the recreation causing the video to play 2x (usually the second one is about 2000ms behind). This does not happen on the Android version

I believe what is happening is when VideoPlayer detects the parent element has changed it recreates itself, but during that recreation process does not fully dispose of the previous object, or looses reference to it on the iOS version, so essentially you will have inaccessible video objects playing with no way to access them build up over time.

**Comment by adamfisher** [comment]
Improvements and/or fixes have been made in version 2.2.0. Please see the [release notes](https://github.com/adamfisher/Xamarin.Forms.VideoPlayer/releases/tag/2.2.0) for more information. The NuGet package should be published shortly.
