### ISSUE TITLE
How i can show progress bar if DisplayControls="False"

### ISSUE THREAD

**Issue by patilhitesh** [adamfisher/Xamarin.Forms.VideoPlayer#84]
I tried your sample,  in that i didn't get any way to show progress of playing video. Is there any way to do that, when i make DisplayControls false?

**Comment by adamfisher** [comment]
It is largely up to the native platform what they choose to do when you hide the default controls. On most platforms the controls disappear automatically after a few seconds. The `DisplayControls` option is only if you want to permanently turn off display of the controls so you can implement your own custom buttons and bind them to the various player commands. The Chill Player's VideoPlayerQueuePage.xaml is a good example of this.
