### ISSUE TITLE
Duplicate launcher icon named "Octane.Xamarin.Forms.VideoPlayer" 

### ISSUE THREAD

**Issue by khuongntrd** [adamfisher/Xamarin.Forms.VideoPlayer#90]
The integration with Xamarin Forms is working, video play well but app installed in android device with 2 launcher icons, one with my app name and one with "Octane.Xamarin.Forms.VideoPlayer". I'm check compiled AndroidManifest.xml file and got additional activity like this:

` <activity android:configChanges="orientation|screenSize" android:icon="@drawable/icon" android:label="Octane.Xamarin.Forms.VideoPlayer" android:name="md5ae95e19a8a406422c07caec4fc239b30.MainActivity">
      <intent-filter>
        <action android:name="android.intent.action.MAIN" />
        <category android:name="android.intent.category.LAUNCHER" />
      </intent-filter>
    </activity>`

**Comment by Mason-Watts** [comment]
I'm encountering the same behavior. @KhuongNtrd were you able to solve this issue? Or, @adamfisher is this behavior something you've experienced before or know the cause of? Thanks!

**Comment by ryanherman** [comment]
How did you get rid of the additional launcher icon with the label - octane.xamarin.forms.videoplayer?  I do not see the additional activity in the AndroidManifest and cannot find anywhere why it is adding it?
