### ISSUE TITLE
We need to buy this control..but

### ISSUE THREAD

**Issue by balvvant** [adamfisher/Xamarin.Forms.VideoPlayer#92]
Hi,
We would like to buy license of this control but we have some basic queries as we could not find some solution using demo control. If you can help us with following queries it will help us buying decision ASAP. this is a urgent requirement.

1. How to play a YouTube Video
2. How to play normal video (mp4)
3. In our page we have half page as video and half page other info in portrait mode. But when we goto landscape mode we want the video to goto full screen mode. and when we goto Portrait mode it should be back to normal earlier size.

Thanks in advance.

**Comment by adamfisher** [comment]
The Chill Player example application included in this repository have the examples you desire. The `MainMenuPage.xaml` and code-behind show how to play an MP4 file included as an embedded resource. The `VideoPlayerQueuePage.xaml` and corresponding code-behind show how to play YouTube and Vimeo video files. You will want to look into using the official APIs Google provides though to get a video URL from them officially. The example included in the `VideoPlayerQueuePage.xaml` is using a markup extension which you could include in your solution. It's a great way to try it out.

As for customization of fullscreen based on device orientation, the player does not support fullscreen out of the box so you will want to implement a [Xamarin Forms custom renderer](https://developer.xamarin.com/guides/xamarin-forms/application-fundamentals/custom-renderer/) and extend `VideoPlayerRenderer` in your platform-specific projects. This will give you control of the native player and allow you to add on the custom functionality you need for customizing fullscreen mode for portrait vs landscape orientation.
