### ISSUE TITLE
Upgrading nuget to 2.1.0 gives incompatible message

### ISSUE THREAD

**Issue by pdougla002** [adamfisher/Xamarin.Forms.VideoPlayer#93]
Hi Adam, I get this when trying to install the latest nuget.
Could not install package 'Octane.Xam.VideoPlayer 2.1.0'. You are trying to install this package into a project that targets '.NETPortable,Version=v4.5,Profile=Profile111', but the package does not contain any assembly references or content files that are compatible with that framework. For more information, contact the package author. Thanks, if you have any advice. PD

**Comment by adamfisher** [comment]
Duplicate of #91

**Comment by pdougla002** [comment]
Perfecto, I figured. Thank you
