### ISSUE TITLE
Purchased License and Never Got a Key

### ISSUE THREAD

**Issue by eopeter** [adamfisher/Xamarin.Forms.VideoPlayer#94]
I purchased the license 12 days ago and never got a key. App crashes complaining about license

**Comment by adamfisher** [comment]
I do not see any outstanding license requests. Did you follow the [Getting Started Guide](https://github.com/adamfisher/Xamarin.Forms.VideoPlayer/blob/master/GettingStarted.md) to request your license key? If so, you might also want to check you don't have anything in spam. It will be coming from an Outlook email address and have "Xamarin Forms Video Player License Key" in the subject line.

**Comment by eopeter** [comment]
Ahaa!! It is in my SPAM folder. Fix your email sender...haha. Thanks
